dock cmd

diff --git a/tools/dock b/tools/dock
--- a/tools/dock
+++ b/tools/dock
@@ -23,6 +23,10 @@ DEBUG=:
 red='\e[0;31m';  RED='\e[1;31m';  green='\e[0;32m';  GREEN='\e[1;32m';  yellow='\e[0;33m';   YELLOW='\e[1;33m';
 blue='\e[0;34m'; BLUE='\e[1;34m'; cyan='\e[0;36m';   CYAN='\e[1;36m';   magenta='\e[0;35m';  NCOL='\e[0m';
 
+
+PATH_FULL=$(realpath "$BASH_SOURCE")
+PATH_DIR="${PATH_FULL%/*}"
+
 #user setting
 account=vc.integrator
 home_dir="/data001/${account}"
@@ -232,17 +236,27 @@ function formatprint(){
 
 function docklist(){
 ## ---------------------------------------------------------------------------
-# $1: ps|images
-# $2: --all|--size
+# $1: ps|images|vol|list
+# $2: detail option
     $DEBUG "[$1] [$2] [$3]"
-    list_cmd=$1
-    formatprint docker images --format '{{.CreatedAt}}|{{.Size}}|{{.ID}}|{{.Tag}}|{{.Repository}}|' ${@:2}; 
-    if [ "$list_cmd" = "ps" ]; then echo "Wait 10s... to get size of container!!"
-        formatprint docker ps --format '{{.CreatedAt}}|{{.Ports}}|{{.State}}|{{.Status}}|{{.Size}}|{{.ID}}|{{.Names}}|{{.Image}}|' ${@:2}; 
-    else 
-        formatprint docker ps --format '{{.CreatedAt}}|{{.Ports}}|{{.State}}|{{.Status}}|{{.ID}}|{{.Names}}|{{.Image}}|' ${@:2};  
-    fi
-    formatprint docker volume ls --format '{{.Driver}}|{{.Mountpoint}}|{{.Name}}|' ${@:2}
+    local cmd=$1 option=$2 
+    local format_img format_ps format_vol
+    format_img='{{.CreatedAt}}|{{.Size}}|{{.ID}}|{{.Tag}}|{{.Repository}}|' 
+     format_ps='{{.CreatedAt}}|{{.Ports}}|{{.State}}|{{.Status}}|{{.ID}}|{{.Names}}|{{.Image}}|'
+    [ "$option" = "--size" ] && format_ps=${format_ps/"{{.Status}}"/"{{.Status}}|{{.Size}}"}
+    format_vol='{{.Driver}}|{{.Mountpoint}}|{{.Name}}|'
+    
+    #echo "[$1] [$2] [$3]"
+    
+    case $cmd in
+        image|images)   formatprint docker images --format "$format_img" ${@:2}
+        ;; ps)          formatprint docker ps --format "$format_ps" ${@:2}
+        ;; vol|volume)  formatprint docker volume ls --format "$format_vol" ${@:2}
+        ;; *) 
+            formatprint docker images --format "$format_img" 
+            formatprint docker ps --format "$format_ps"
+            formatprint docker volume ls --format "$format_vol" 
+    esac
 }
 
 
@@ -378,7 +392,7 @@ function dockstoprm(){
     local cmd=$1
     local param="${@:2}"
     local cntr_name
-    [ -z "${param}" ] && docklist ps --all
+    [ -z "${param}" ] && docklist ps
     printf "${red}========== stop & remove container ========== ${NCOL}\n"
     echo "Multiple container can be input with space ex) cntr1 cntr2 cntr3 ..."
     read -p "must input Container [Name| ID]: " cntr_name
@@ -421,7 +435,7 @@ function dockrmi(){
 function dockexec(){
 ## ---------------------------------------------------------------------------
 
-    docklist ps --all
+    docklist ps
     printf "${red}========== "${FUNCNAME[0]}" ========== ${NCOL}\n"
     local recent_name=$(docker ps --format '{{.Names}}' |sed -n '1p'| sed 's/.*\///p')
 
@@ -493,10 +507,92 @@ function dockinfo(){
 }
 
 
+
+function dockenter(){
+## ---------------------------------------------------------------------------
+##https://github.com/jpetazzo/nsenter/
+##https://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/
+    local IMPORTENV PID ENVIRON OPTS LAZY_SUDO
+    
+    if ! command -v nsenter > /dev/null ; then echo "nsenter is not existed"; exit 1; fi
+
+    IMPORTENV=$PATH_DIR/importenv
+    PID=$(docker inspect --format "{{.State.Pid}}" "$1")
+    ENVIRON="/proc/$PID/environ"
+    OPTS="--target $PID --mount --uts --ipc --net --pid "
+    
+    [ -z "$PID" ] && exit 1
+    shift
+
+    if [ "$(id -u)" -ne "0" ]; then
+        which sudo > /dev/null
+        if [ "$?" -eq "0" ]; then
+          LAZY_SUDO="sudo "
+        else
+          echo "Warning: Cannot find sudo; Invoking nsenter as the user $USER." >&2
+        fi
+    fi
+
+    # env is to clear all host environment variables and set then anew
+    if [ $# -lt 1 ]; then
+        # No arguments, default to `su` which executes the default login shell
+        echorun $LAZY_SUDO "$IMPORTENV" "$ENVIRON" nsenter $OPTS su -m root
+    else
+        # Has command
+        # "$@" is magic in bash, and needs to be in the invocation
+        echorun $LAZY_SUDO "$IMPORTENV" "$ENVIRON" nsenter $OPTS "$@"
+    fi
+}
+
+
+function dockcmd(){
+## ---------------------------------------------------------------------------
+# 도커에 진입하지 않고 도커외부에서 docker 없는 명령을 실행시킨다.
+    local cntr_name cmd path_host path_real file_sys DEV MOUNT JUNK SUBROOT SUBPATH DEVDEC
+    
+    docklist ps 
+    printf "${red}========== "${FUNCNAME[0]}" ========== ${NCOL}\n"
+    read -p "must input Container [Name]: " cntr_name
+    read -p "command [default:mount| othercmd]: " cmd
+    [ -n "$cmd" ] && { dockenter $cntr_name -- sh -c '"$cmd"'; exit 0; }
+    read -p "must input full path in HOST: " path_host
+    [ -d "$path_host" ] || { echo "dir not exist"; return 1; }
+    read -p "must input path in Container: " path_cntr
+
+
+
+    path_real=$(readlink --canonicalize $path_host)
+    file_sys=$(df -P $path_real | tail -n 1 | awk '{print $6}')
+
+    while read DEV MOUNT JUNK
+    do [ $MOUNT = $file_sys ] && break
+    done </proc/mounts
+    [ $MOUNT = $file_sys ] # Sanity check!
+
+    while read A B C SUBROOT MOUNT JUNK
+    do [ $MOUNT = $file_sys ] && break
+    done < /proc/self/mountinfo
+    [ $MOUNT = $file_sys ] # Moar sanity check!
+
+    SUBPATH=$(echo $path_real | sed s,^$file_sys,,)
+    DEVDEC=$(printf "%d %d" $(stat --format "0x%t 0x%T" $DEV))
+
+    dockenter $cntr_name -- sh -c "[ -b $DEV ] || mknod --mode 0600 $DEV b $DEVDEC"
+    dockenter $cntr_name -- mkdir /tmpmnt
+    dockenter $cntr_name -- mount $DEV /tmpmnt
+    dockenter $cntr_name -- mkdir -p $path_cntr
+    dockenter $cntr_name -- mount -o bind /tmpmnt/$SUBROOT/$SUBPATH $path_cntr
+    dockenter $cntr_name -- umount /tmpmnt
+    dockenter $cntr_name -- rmdir /tmpmnt
+    dockenter $cntr_name -- ls $path_cntr
+
+}
+
+
 function dockcopy(){
 ## ---------------------------------------------------------------------------
     if [ -z "${cntr_name}" ];then 
-        docklist ps --all
+        docklist ps
     read -p "must input Container [Name| ID]: " cntr_name;
     fi
     echorun docker exec -t $cntr_name /bin/bash -c 'tree -aL 2 /data001/vc.integrator'
@@ -541,7 +637,7 @@ MENU=(
     'list(img&cntr)' 'build(dockerfile)' 'start(run++ img)' 'exec(attach cntr)' 
     'hello(testimg)' 'run(just run)' 'stop(&rm ctnr)' 'remove(img)' 'clean(prune all)' 
     'debug(log)' 'find(in arti)' 'pull(from arti)' 'push(to arti)' 'down(dockerfile)' 
-    'copy(between host)' 'help'
+    'cmd(exe docker)' 'copy(between host)' 'help'
 )
 
 function handler_menu(){
@@ -586,7 +682,7 @@ function dockmenu(){
 local ret=0
     case "$1" in
         list)           docklist "${@:2}"                                     ;;
-          image|images|ps)    docklist "${@:1}"                               ;;
+          image|images|ps|vol|volume)    docklist "${@:1}"                    ;;
         build)          dockbuild "${@:2}"                                    ;;
           hello)        dockhello;                                            ;;
         start)          dockstart;                                            ;;
@@ -598,6 +694,7 @@ local ret=0
           clean)        dockclean;                                            ;;
         pull|push|find) dockerhub "${@:1}"                                    ;;
           down)         dockdown  "${@:2}"                                    ;;
+        cmd)            dockcmd "${@:2}"                                      ;;
         copy)           dockcopy "${@:2}"                                     ;;
         info|status)    dockinfo "${@:2}"                                     ;;
         ende_code)      "${@:1}"                                              ;;
