reppforall for revv, lots of changes

diff --git a/tools/prelibrary b/tools/prelibrary
--- a/tools/prelibrary
+++ b/tools/prelibrary
@@ -8,9 +8,10 @@
 #### predefined variable
 #### ============================================================================
 ## color definition, BOLD is brighter
+## 0|1 = normal|bold;  30:black ~ 37:white
 red='\e[0;31m';     RED='\e[1;31m';     green='\e[0;32m';       GREEN='\e[1;32m';
 yellow='\e[0;33m';  YELLOW='\e[1;33m';  blue='\e[0;34m';        BLUE='\e[1;34m';
-cyan='\e[0;36m';    CYAN='\e[1;36m';    magenta='\e[0;35m';     purple='\e[0;35m';
+magenta='\e[0;35m'; PURPLE='\e[1;35m';  cyan='\e[0;36m';        CYAN='\e[1;36m';
 NCOL='\e[0m';       outline=${cyan};    inline=${yellow};
 
 file_error=~/.repoconfig/repo.error
@@ -42,8 +43,8 @@ info()    { log "${GREEN}INFO: ${NCOL} ${*}"  ;}
 warn()    { log "${YELLOW}WARN: ${NCOL} ${*}" ;}
 err()     { log "${RED}ERROR: ${NCOL} ${*}" > /dev/stderr ;}
 
-#${2:+[$2] }: if $2 exist, use '[$2] '
-#${_line:(${2:+3}+${#2})}: if $2 is exist, skip 3 '-' chars for '[] ' chars
+#${2:+[$2] }: $2 번째 인자가 존재하면 '[$2] '를 사용
+#${_line:(${2:+3}+${#2})}: $2 인자가 존재하면, '[] '표시를 위해 '---' 3글자를 건너띄어라
 ## supprort 2 _line type: bar inline, bar outline
 ## bar [inline|outline] "text1"
 bar()    { printf "\n${!1}%s%s ${NCOL}\n" "${2:+[$2] }" "${_line:(${2:+3}+${#2})}" ;}
@@ -57,11 +58,15 @@ under()  {
 #usage
 # start: laptime reset;
 #   lap: laptime
-laptime() {
-    local _now=$(date +%s.%N);
+laptime() {  local _now=$(date +%s.%N);
     [[ $1 == reset ]] && { _lapn=0; _lapc=$_now; return; }
     echo "<<<< $(( _lapn++ )) [ $(echo "$_now - $_lapc" | bc) ]";
 }
+
+mark=('/' '-' '\' '|')
+#progreass는 반복문안에서 호출되어야 함.
+#                    색상 시계 문자열    문자열 |  제목       시계                   내용
+progress()  { printf "${!1}%s%s ${NCOL}%b\r" "${2:+$2 }" "${mark[$((count%4))]}" "$3" ;}
 
 showcolor(){
     printf "${red}%8s\t%-24s${NCOL}\n"   "red"     "abcdefg 0123456789 ---- ===="
@@ -75,22 +80,22 @@ showcolor(){
     printf "${cyan}%8s\t%-24s${NCOL}\n"  "cyan"    "abcdefg 0123456789 ---- ===="
     printf "${CYAN}%8s\t%-24s${NCOL}\n"  "CYAN"    "abcdefg 0123456789 ---- ===="
     printf "${magenta}%8s\t%-24s${NCOL}\n" "magenta" "abcdefg 0123456789 ---- ===="
-    printf "${purple}%8s\t%-24s${NCOL}\n" "purple"  "abcdefg 0123456789 ---- ===="
+    printf "${PURPLE}%8s\t%-24s${NCOL}\n" "PURPLE"  "abcdefg 0123456789 ---- ===="
 }
 
 showline(){
-printf 'usage:        log "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":';         log "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:       dlog "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":';        dlog "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:      dnlog "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":';       dnlog "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:       clog "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":';        clog "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:       info "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":';        info "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:       warn "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":';        warn "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:        err "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":';         err "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:       wave "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":';        wave "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:      under "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":';       under "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:bbar purple "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":'; bbar purple "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage: bar inline "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":'; bar inline  "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
-printf 'usage:bar outline "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":'; bar outline "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:        log "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t';         log "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:       dlog "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t';        dlog "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:      dnlog "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t';       dnlog "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:       clog "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t';        clog "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:       info "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t';        info "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:       warn "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t';        warn "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:        err "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t';         err "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:       wave "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t';        wave "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:      under "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t';       under "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage: bar inline "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t'; bar inline  "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:bar outline "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t'; bar outline "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
+printf 'usage:bbar PURPLE "|HEAD $PPID" "BODY Hello World \\t\\tcharEND\\n":\t\t\t'; bbar PURPLE "|HEAD $PPID" "BODY Hello World \t\tcharEND\n"
 }
 
 #pCount() { tee >(let sum="$(wc -l) + ${1:-0}"; clog "#count:" "$((sum<0?0:+sum))" ); }
@@ -191,33 +196,45 @@ function checkifSHA(){
 }
 
 
-function  getServer() {
+function  revvserver_item() {
 ## ---------------------------------------------------------------------------
 ## return remote (gerrit server) info as a various type
-## format: getServer [29420|na|vgit|lamp|review] [port|http|sub|domain|subdomain|path|url|remote|debug]
+## format: revvserver_item [29420|na|vgit|lamp|review]     [port|http|sub|domain|subdomain|path|url|remote|debug]
 ## exception: vgitxxx lampxxx will return only postfix after delimter _
 ##            aaa-bbb같이 -를 포함하는 sub은 -앞의 string(aaa)만 사용한다.
 
-    local key=$1
-    local _item=$(revvserver de $key |awk -F '|' '{print $2}')
+    local ret=0 remote=$1 prn _line remote_key
+    _line=$(revvserver de $remote)
+    if [ -f ${REPPFILE_JSON_REMOTE} ] && [ "$?" -ne 0 ] || [ -z "$_line" ] ;
+    then _line=$(revvserver de $(cat ${REPPFILE_JSON_REMOTE}|jq -rM --arg jq_remote "$remote" '.[]|select(.name == $jq_remote) | .review'))
+        if [ -z "$_line" ]; then
+            remote_key=$(cat ${REPPFILE_JSON_REMOTE}|jq -rM --arg jq_remote "$remote" '.[]|select(.name == $jq_remote) | .fetch'| cut -d'|' -f1)
+            _line=$(revvserver de $remote_key )
+        fi
+    fi
+    [ -z "$_line" ] && { err "server infomation is null"; return 1; }
+
+    local _item=$(echo "$_line"  | cut -d'|' -f2)
     local return_type=$2
 
-    case ${return_type} in                                                                    # return value
-            http)    echo "${_item%:*}"                                                       # http://vgit.lge.com/na
-    ;;      port)    echo "${_item##*:}"                                                      # 29420
-    #;;       sub)    echo "${_item#*://}"| awk -F[./:] '{sub(/-.*/,"",$1);print $1}'
-    ;;       sub)    echo "${_item#*://}"| awk -F[./:] '{print $1}'                           # vgit
-    ;;    domain)    echo "${_item#*://}"| awk -F[./:] '{print $2"."$3}'                      # lge.com
-    ;; subdomain)    echo "${_item#*://}"| awk -F[./:] '{print $1"."$2"."$3}'                 # vgit.lge.com
-    ;;      path)    echo "${_item#*://}"| awk -F[./:] '{print $4}'                           # na
-    ;;       url)    echo "${_item#*://}"| awk -F[./:] '{$4="/"$4;gsub(/\/none_.*/,"",$4);print $1"."$2"."$3$4}'  # vgit.lge.com/na
-    ;;    remote)    echo "${_item#*://}"| awk -F[./:] '{if ($4=="devops_test") print $4; else print $1"_"$4}'   # vgit_na
-    ;;      pass)    revvserver de $key  | awk -F '[[:space:]]*\\|'  '{print $4}'             # N4lIA0SoQAoUfxlmCZudjNA12344
-    ;;      user)    revvserver de $key  | awk -F '[[:space:]]*\\|'  '{print $3}'             # vc.integrator
-    ;;     debug)    echo "${_item}"                                                          # http://vgit.lge.com/na:29420
-    ;;         *)    echo "NULL";                                                             # vgit.lge.com/na:29420
+    case ${return_type} in                                                                      # return value
+            http)    prn=$(echo "${_item%:*}")                                                  # http://vgit.lge.com/na
+    ;;      port)    prn=$(echo "${_item##*:}")                                                 # 29420
+    #;;       sub)   prn=$( echo "${_item#*://}"| awk -F[./:] '{sub(/-.*/,"",$1);print $1}'
+    ;;       sub)    prn=$(echo "${_item#*://}"| awk -F[./:] '{print $1}')                      # vgit
+    ;;    domain)    prn=$(echo "${_item#*://}"| awk -F[./:] '{print $2"."$3}')                 # lge.com
+    ;; subdomain)    prn=$(echo "${_item#*://}"| awk -F[./:] '{print $1"."$2"."$3}')            # vgit.lge.com
+    ;;      path)    prn=$(echo "${_item#*://}"| awk -F[./:] '{print $4}')                      # na
+    ;;       url)    prn=$(echo "${_item#*://}"| awk -F[./:] '{$4="/"$4;gsub(/\/none_.*/,"",$4);print $1"."$2"."$3$4}')  # vgit.lge.com/na
+    ;;    remote)    prn=$(echo "${_item#*://}"| awk -F[./:] '{if ($4=="devops_test") print $4; else print $1"_"$4}')    # vgit_na
+    ;;       key)    prn=$(echo "$_line"  | cut -d'|' -f1)                                      # vgit_29420
+    ;;      user)    prn=$(echo "$_line"  | cut -d'|' -f3)                                      # vc.integrator
+    ;;      pass)    prn=$(echo "$_line"  | cut -d'|' -f4)                                      # N4lIA0SoQAoUfxlmCZudjNA12344
+    ;;     alias)    prn=$(echo "$_line"  | cut -d'|' -f5)                                      # vgit_na,na
+    ;;     debug)    prn=$(echo "${_item}")                                                     # http://vgit.lge.com/na:29420
+    ;;         *)    prn='';  ret=1                                                             # error
     esac
-
+    [ -n "$prn" ] && { echo "$prn" |xargs; return 0; }  || return 1
 }
 
 
@@ -226,19 +243,20 @@ function revvserver(){
 # encoding as variable: code env <keyname> <key>
 # encoding as file: code en <keyfile> <key>
 # decode de <keyfile>
-local temp temp_var
-local cmd=$1 tag=$2 key=$3
+local temp_var setflag ret=0
+local cmd=$1 tag=$2
     case $cmd in
        gen) #default server 접속정보 파일인 ~/.key_server를 생성한다.
             clog ".key_server" "is generated, \nplease add your server info with http key from: https://gerrit.url.com/settings/#HTTPCredentials\n"
         cat <<-EOF  >.key_server
-			REMOTE,KEY   |URL to GERRIT                                         |ACCOUNT         |HTTP KEY
-			vgit_na      |http://vgit.lge.com/na:29420                          |vc.integrator   |ex)N4lIA0SoQAoUfxlmCZudjNA1
-			vgit_eu      |http://vgit.lge.com/eu:29430                          |vc.integrator   |~~~
-			vgit_as      |http://vgit.lge.com/as:29440                          |vc.integrator   |~~~
-			vgit_adas    |http://vgit.lge.com/adas:29550                        |vc.integrator   |
-			devops_test  |http://vgit.lge.com/devops_test:29999                 |vc.integrator   |
-			review       |http://lamp.lge.com/review:29418                      |vc.integrator   |
+            # REMOTEKEY must be made by 'SubDomain + Port'
+			REMOTEKEY       |URL to GERRIT                                         |ACCOUNT         |HTTP KEY                      |ALIAS
+			vgit_29420      |http://vgit.lge.com/na:29420                          |vc.integrator   |ex)N4lIA0SoQAoUfxlmCZudjNA1   |na,vgit_na
+			vgit_29430      |http://vgit.lge.com/eu:29430                          |vc.integrator   |~~~                           |eu,vgit_eu
+			vgit_29440      |http://vgit.lge.com/as:29440                          |vc.integrator   |~~~                           |as,vgit_as
+			vgit_29550      |http://vgit.lge.com/adas:29550                        |vc.integrator   |                              |adas,vgit_adas
+			vgit_29999      |http://vgit.lge.com/devops_test:29999                 |vc.integrator   |                              |devops,test,devops_test
+			lamp_29418      |http://lamp.lge.com/review:29418                      |vc.integrator   |                              |review,lampauto,lamp
 EOF
         cat .key_server
 
@@ -247,36 +265,41 @@ EOF
                 clog "$HOME/.key_server will be converted to $HOME/.key_server.en with encrypting"
                 cat $HOME/.key_server | openssl enc -base64 -e -aes-256-cbc -nosalt -pbkdf2  -pass pass:garbageKey > $HOME/.key_server.en
                 rm -f $HOME/.key_server
-            else
-                clog "$HOME/.key_server.en" "could be updated by '$FUNCNAME editing' [$HOME/.key_server]"
-                err "You must create server connection info, use '$FUNCNAME gen'"; return 1
+            else ret=1
+                clog "$HOME/.key_server.en" "could be updated by '$revv server editing' [$HOME/.key_server]"
+                err "You must create server connection info, use '$revv server gen'";
             fi
 
     ;;edit) #~/.key_server.en으로 부터 ~/.key_server를 생성하여 편집할수 있게 해준다.
             cat $HOME/.key_server.en | openssl enc -base64 -d -aes-256-cbc -nosalt -pbkdf2 -pass pass:garbageKey >$HOME/.key_server
             clog "$HOME/.key_server" "is decrypted from $HOME/.key_server.en"
-            [ -f "$HOME/.key_server" ] && cat $HOME/.key_server || { err "You must create server connection info, use '$FUNCNAME gen'"; return 1; }
+            [ -f "$HOME/.key_server" ] && cat $HOME/.key_server || { ret=1; err "You must create server connection info, use '$revv server gen'"; }
 
     ;;  de) #~/.key_server.en에서 server정보를 획득해온다.
+            #함수결과값으로 echo와 return을 모두 사용함으로 log출력은 stderr로 출력해야 한다.
+            #이름이 정확히 key에 match하며 key를 해당 line을 리턴, 그렇지 않으면 alias에서 확인, 그렇지 않으면 전체 line에서 확인하여 해당 line을 리턴
             if [ -f $HOME/.key_server.en ]; then
-                temp_var=$(cat $HOME/.key_server.en | openssl enc -base64 -d -aes-256-cbc -nosalt -pbkdf2 -pass pass:garbageKey |\
-                  awk -v tag="$tag" -F '[[:space:]]*\\|' '$1 == tag{print $0}')
-                if [ -n "$temp_var" ];then
-                    echo $temp_var && return 0
-                else temp_var=$(cat $HOME/.key_server.en | openssl enc -base64 -d -aes-256-cbc -nosalt -pbkdf2 -pass pass:garbageKey |\
-                  awk -v tag="$tag" -F '[[:space:]]*\\|' '$2 ~ tag && !found {print $0; found=1}')
-                    echo $temp_var && return 0
+                #cache match이면 그냥 바로 return
+                [ "$REVV_TAG" = "$tag" ] && { echo $REVV_SERVER; return 0; }
+                #REMOTEKEY이후부터 출력
+                [[ $- == *x* ]] && { set +x ; setflag=true; }
+                temp_var=$(cat "$HOME/.key_server.en" | openssl enc -base64 -d -aes-256-cbc -nosalt -pbkdf2 -pass pass:garbageKey | awk -F'|' 'p{print} $1 ~ /^REMOTEKEY */ {p=1}')
+                REVV_SERVER=$(echo "$temp_var" | awk -v tag="$tag" -F '[[:space:]]*\\|' '
+                    $1 == tag   {print; exit}   #먼저 match하면 출력후 종료
+                    $5 ~ tag    {print; exit}
+                    $2 ~ tag    {print; exit} ')
+                if [ -n "$REVV_SERVER" ]; then  REVV_TAG=$tag; echo "$REVV_SERVER";
+                else ret=1
+                    warn "matched http key is not existed or incorrect!" >2
+                    clog "guide" "run 'revv server edit' and edit proper server info in .key_server"  >2
                 fi
-
-                err "matched http key is not existed or incorrect!";
-                clog "guide" "run '$FUNCNAME edit' and edit proper server info in .key_server"
-                return  1;
+                ${setflag:-false} && { set -x ; setflag=false; }
             else
-                err "You must create server connection info, use '$FUNCNAME gen'"; return 1
+                err "You must create server connection info, use 'revv server gen'" >2 ; ret=1
             fi
 
-    ;;check|info) #getServer 함수 test용으로 모든 format대로 제대로 출력하는지 확인할수 있다.
-            test_getServer $cmd
+    ;;check|info) #revvserver_item 함수 test용으로 모든 format대로 제대로 출력하는지 확인할수 있다.
+            test_revvserver_item $cmd
     ;;help) cat <<- EOF
 			usage) revv server <cmd> <option>
 
@@ -286,15 +309,16 @@ EOF
 			revv server    de vgit_na     #search vgit_na server and get info of it from .key_server.en
 			revv server  show             #show current server info from .key_server.en
 			revv server check             #check connection of server. if success, key is correct!
-			revv server  info             #check connection of server and format of getServer api
+			revv server  info             #check connection of server and format of revvserver_item api
 EOF
     ;;show|*)  #현재 .key_server파일을 보여준다.
-            [ ! -f $HOME/.key_server.en ] && err "You must create server connection info, use '$FUNCNAME gen'"
+            [ ! -f $HOME/.key_server.en ] && err "You must create server connection info, use '$revv server gen'"
             cat $HOME/.key_server.en | openssl enc -base64 -d -aes-256-cbc -nosalt -pbkdf2 -pass pass:garbageKey
 
             clog "You can refer:" "'revv server help'"
 
     esac
+    return $ret
 }
 
 
