add rep script as initial version

diff --git a/tools/prelibrary b/tools/prelibrary
--- a/tools/prelibrary
+++ b/tools/prelibrary
@@ -1,6 +1,7 @@
+#!/bin/bash
 # ===============================================================================
-# mail: joongkeun.kim@lge.com/av9300@gmail.com
-# this file should be sourced early step in script: source ./prelibrary
+#  mail: joongkeun.kim@lge.com, av9300@gmail.com
+#  this file should be sourced early step in script: source ./prelibrary
 # ===============================================================================
 #
 #### ============================================================================
@@ -10,10 +11,67 @@
 red='\e[0;31m';     RED='\e[1;31m';     green='\e[0;32m';       GREEN='\e[1;32m';
 yellow='\e[0;33m';  YELLOW='\e[1;33m';  blue='\e[0;34m';        BLUE='\e[1;34m';
 cyan='\e[0;36m';    CYAN='\e[1;36m';    magenta='\e[0;35m';     brown='\e[0;33m';
-NCOL='\e[0m';
+NCOL='\e[0m';       outline=${cyan};    inline=${yellow}; 
 
-## default variable
-SCRIPT_DIR=${BASH_SOURCE%/*}
+file_error=~/.repoconfig/repo.error
+
+## ---------------------------------------------------------------------------
+# log message to stderr
+# $1: message
+line="--------------------------------------------------------------------------------------"
+log()   { printf "%b\\n" "${*}"  ;}
+info()  { log "${GREEN}INFO: ${NCOL} ${*}"  ;}
+warn()  { log "${YELLOW}WARN: ${NCOL} ${*}" ;}
+err()   { log "${RED}ERROR: ${NCOL} ${*}"   ;}
+
+#${2:+[$2] }: if $2 exist, use '[$2] '
+#${line:(${2:+3}+${#2})}: if $2 is exist, skip 3 '-' chars for '[] ' chars
+bar()  { printf "${!1}%s%s ${NCOL}\n\n" "${2:+[$2] }" "${line:(${2:+3}+${#2})}" ;}
+
+function printToFILE(){ 
+## ---------------------------------------------------------------------------
+## printToFILE $(mktemp) title contents title-color
+## $1: file, ## $2: head-msg, ## $3: content, ## $4: tail-msg
+
+    case $1 in
+    create) printfile=$(mktemp);;
+    flush) 
+        if [ -f "$printfile" ]; then 
+            cat $printfile
+            rm -f $printfile; 
+        fi ;;
+    no) printf "${yellow}%s %s ${NCOL}\n  %s\n" "$2" "${line:${#2}}" "$3" ;;
+    *) printf "${yellow}%s %s ${NCOL}\n  %s\n" "$2" "${line:${#2}}" "$3" >> $printfile;;
+    esac
+}
+
+
+function showRUN(){ echo "\$ $@" ; "$@" ; }
+## ---------------------------------------------------------------------------
+# show command before execution
+# $1: command
+
+
+## ---------------------------------------------------------------------------
+# $1: message
+# $2: exit code
+function die() { local m="$1"; local e=${2-1}; echo "$m"; exit $e; }
+function is_root() { [ $(id -u) -eq 0 ] && echo 1 || echo 0 ;}
+
+
+function getCurrentIP(){
+## ---------------------------------------------------------------------------
+# get current ip-address
+
+    default_ip=172.0.0.1
+
+    readarray -t a <<<"$(hostname -I) $SSH_CONNECTION"
+    for ip in ${a[@]}; do
+        max=$(grep -o $ip <<< ${a[*]} | wc -l)
+        if [ $max -eq 2 ] ;then default_ip=$ip && echo $ip && break; fi
+    done
+}
+
 
 
 #### ============================================================================
@@ -23,40 +81,39 @@ function show_menu_do(){
 ## ---------------------------------------------------------------------------
 # [call] show_menu_do "${INPUT}" #inputs should be divided with white spaces
 # show the menu and make user select one from it.
-
-local lines
-#should be up one token
-lines=($1)
-if [[ ${#lines[@]} = 0 ]]; then
-    echo "Not found"
-    return 1
-fi
-local pathname
-local choice
-if [[ ${#lines[@]} > 1 ]]; then
-    while [[ -z "$pathname" ]]; do
-        local index=1
-        local line
-        for line in ${lines[@]}; do
-            printf "%6s %s\n" "[$index]" $line
-            index=$(($index + 1))
+    local lines
+    #should be up one token
+    lines=($1)
+    if [[ ${#lines[@]} = 0 ]]; then
+        echo "Not found"
+        return 1
+    fi
+    local pathname
+    local choice
+    if [[ ${#lines[@]} > 1 ]]; then
+        while [[ -z "$pathname" ]]; do
+            local index=1
+            local line
+            for line in ${lines[@]}; do
+                printf "%6s %s\n" "[$index]" $line
+                index=$(($index + 1))
+            done
+            echo
+            echo -n "Select one: "
+            unset choice
+            read choice
+            if [[ $choice -gt ${#lines[@]} || $choice -lt 1 ]]; then
+                echo "Invalid choice"
+                continue
+            fi
+            pathname=${lines[$(($choice-1))]}
         done
-        echo
-        echo -n "Select one: "
-        unset choice
-        read choice
-        if [[ $choice -gt ${#lines[@]} || $choice -lt 1 ]]; then
-            echo "Invalid choice"
-            continue
-        fi
-        pathname=${lines[$(($choice-1))]}
-    done
-else
-    # even though zsh arrays are 1-based, $foo[0] is an alias for $foo[1]
-    pathname=${lines[0]}
-fi
- RET=$pathname
- return 0
+    else
+        # even though zsh arrays are 1-based, $foo[0] is an alias for $foo[1]
+        pathname=${lines[0]}
+    fi
+     RET=$pathname
+     return 0
 }
 
 
diff --git a/tools/rep1 b/tools/rep1
--- a/tools/rep1
+++ b/tools/rep1
@@ -12,24 +12,36 @@ source ${SCRIPT_DIR}/prelibrary
 #user setting
 account=vc.integrator
 mirror="/data001/${account}"/mirror
-path_mirror=/data001/vc.integrator/mirror
-rm -f ${file_error}
+file_error=~/.repoconfig/repo.error
 
 
 ##--------------------------- Menu Functions --------------------------------
 ##============================================================================
+function showRUN(){ echo "\$ $@" ; "$@" ; }
+function getGitRootPath(){ echo $(git rev-parse --show-toplevel);}
 
-function getGitRootPath(){ 
+function printToFILE(){ 
 ## ---------------------------------------------------------------------------
-# get repo dir path from repo sub directory
-    echo $(git rev-parse --show-toplevel);
+## printToFILE $(mktemp) title contents title-color
+## $1: file, ## $2: head-msg, ## $3: content, ## $4: tail-msg
+    line="--------------------------------------------------------------------------------"
+
+    case $1 in
+    create) printfile=$(mktemp);;
+    flush) 
+        if [ -f "$printfile" ]; then 
+            cat $printfile
+            rm -f $printfile; 
+        fi ;;
+    no) printf "${yellow}%s %s ${NCOL}\n  %s\n" "$2" "${line:${#2}}" "$3" ;;
+    *) printf "${yellow}%s %s ${NCOL}\n  %s\n" "$2" "${line:${#2}}" "$3" >> $printfile;;
+    esac
 }
 
 
 
 function runSSHcheckError(){ 
 ## ---------------------------------------------------------------------------
-# run command, get return code and print guide
     echo "\$ $@" ;"$@" 
     case $? in
      0) ;;
@@ -58,26 +70,24 @@ function runSSHcheckError(){
 
 function runRepoInitcheckError(){ 
 ## ---------------------------------------------------------------------------
-# run command, get return code and print guide
     echo "\$ $@"  
-    "$@" 2> >(tee -a ${file_error})
-    #"$@" | tee -a ${file_error}
-
-    if [ $? -ne 0 ];then runSSHcheckError ssh -p vc.integrator@vgit.lge.com:29430;fi
-
-    
+    #"$@" 2> >(tee -a ${file_error})
+    "$@" | tee -a ${file_error}
+    case $? in
+     0) ;;
+     1) echo Generic error, usually because invalid command line options or malformed configuration;;
+     2) echo Connection failed;;
+    esac
 }
  
  
  
 function runRepoSynccheckError(){ 
 ## ---------------------------------------------------------------------------
-# run command, get return code and print guide
-# ex) runRepoSynccheckError --depth=1 32
-    if [ -z "$2" ]; then read -p "Please input job number to repo sync [enter:auto| number:ex)16| ctrl+c:exit]: " njobs; fi
-    if [ -z $njobs ]; then  njobs=$(( $(nproc --all) / 4)); fi
-    showRUN repo sync -qcj${njobs:-16} --no-tags --no-clone-bundle $1
-
+## ex) runRepoSynccheckError --depth=1 32
+    if [ -z "$2" ]; then read -p "please input job number to repo sync [enter j16| number| ctrl+c]: " njobs; fi
+    repo sync -qcj${njobs:-16} --no-tags --no-clone-bundle $1
+    echo "KKK $@"  
     #"$@" 2> >(tee -a ${file_error})
     "$@" > >(tee -a ${file_error})
     case $? in
@@ -93,7 +103,7 @@ function runRepoSynccheckError(){
 function findFileLocation(){
 ## ---------------------------------------------------------------------------
 ## find input-path up and down, 
-## $1:path name, $2:max depth to sub dir
+## $1:path name, $2:max depth
 ## ex) findFileLocation .repo 5
 ## ex) findFileLocation .git 2
 
@@ -121,8 +131,7 @@ function findFileLocation(){
         ;;
     esac
     #if [ "$1" = "show" ];then 
-        bar inline "repo path"
-        log "${REPO_PATH}"
+        printToFILE no "repo path" "${REPO_PATH}" "${yellow}"
     #fi
 }
 
@@ -130,10 +139,8 @@ function findFileLocation(){
 
 function getRepoCMD(){
 ## ---------------------------------------------------------------------------
-# get repo command from exising repo project
-# $1 show repo command (default: save info to each variable such as REMOTE_URL, BRANCH_REPO, ...)
     findFileLocation .repo/manifests 5
-    if [ -d "${REPO_PATH}" ];then cd ${REPO_PATH};else err "you are not in repo project";exit;fi
+    if [ -d "${REPO_PATH}" ];then cd ${REPO_PATH};else printf "${RED}[error] you are not in repo project${NCOL}";return;fi
     
     local count file_tempa file_tempb 
         
@@ -164,18 +171,28 @@ function getRepoCMD(){
 
     if [ -n "$REFER_MIRROR" ];then EXTRA_OPTION="--reference $REFER_MIRROR"; fi
     if [ "$1" = "show" ];then 
-        bar inline "repo-init cmd"
-        log "repo init -u $REMOTE_URL -b $BRANCH_REPO -m $FILE_MANI --repo-url $REPO_URL $EXTRA_OPTION"
+        printToFILE create
+        printToFILE print "repo-init cmd" "repo init -u $REMOTE_URL -b $BRANCH_REPO -m $FILE_MANI --repo-url $REPO_URL $EXTRA_OPTION" "${yellow}"
+        printToFILE flush
     fi
     return 0
 }
 
 
 
+function getCurrentIP(){
+    default_ip=172.0.0.1
+
+    readarray -t a <<<"$(hostname -I) $SSH_CONNECTION"
+    for ip in ${a[@]}; do
+        max=$(grep -o $ip <<< ${a[*]} | wc -l)
+        if [ $max -eq 2 ] ;then default_ip=$ip && echo $ip && break; fi
+    done
+}
+
+
 function findProperREPLServer(){
 ## ---------------------------------------------------------------------------
-# find replication server 
-# $1 log-file to show result
     local server_PORT=29418
     local server_URL=( lampmg1.lge.com lampgd1.lge.com )
     local file_temp=$(mktemp)
@@ -213,154 +230,138 @@ function findProperREPLServer(){
 
 function repoInit(){
 ## ---------------------------------------------------------------------------
-# repo init helper
-# $1 short repo init command
     #option handle
-    local url revision manifest platform reference depth repo_url extra
-    if ! options=$(getopt -l reference:,depth:,repo-url:,no-clone-bundle,partial-clone,no-tags,mirror -o b:m:p:u: -- "$@")
-    then err 'please check "repo init --help"'; exit 1; fi
-
-    #reset legacy positional parameter except $options
-    eval set -- "$options"
-    while true; do
-        case $1 in
-            #when option has sub option, should shift 2 or just shift
-            -u|--manifest-url)                                          url=$2;         shift 2;;
-            -b|--manifest-branch)                                       revision=$2;    shift 2;;
-            -m|--manifest-name)                                         manifest=$2;    shift 2;;
-            -p|--platform)                                              platform=$2;    shift 2;;
-            --reference)                                                reference=$2;   shift 2;;
-            --depth)                                                    depth=$2;       shift 2;;
-            --repo-url)                                                 repo_url=$2;    shift 2;;
-            #single option that need no additional sub value          
-            #skip single option and remove getopt cmd                 
-            -c|--current-branch)                                  extra="${extra} $1";  shift 1;;
-            --no-clone-bundle|--partial-clone|--no-tags|--mirror) extra="${extra} $1";  shift 1;;
-            --|*)                                                                  shift; break;;
-        esac
+    local repo_URL url_repl url revision manifest opt left
+    while getopts m:b:u:c opt 2> /dev/null; do
+       case $opt in
+          u) url=$OPTARG;;
+          b) revision=$OPTARG;;
+          m) manifest=$OPTARG;; 
+          c) current=$OPTARG;;
+          *) left=${left} $OPTARG;;
+       esac
     done
 
     #revision handle
-    if [ -z "${revision}" ];then
+    if [ -z "${revision}" ]; then 
         printf "usage: rep init -b [branch] [-m manifest.xml] \n";
         bar outline         
         printf "ex: rep init -b lampauto_s_release -m all.xml \n";
         printf "ex: rep init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1 \n";
         printf "ex: rep init -u ssh://lampgd1.lge.com:29418/platform/manifest.git -b lampauto_r_release \n -m lampauto/lampauto-gm-recent.xml --reference=/data001/vc.integrator/mirror/lampauto_r_release/ \n --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git \n";
+        echo "${revision}"
         exit
     fi
+    
+    local mirror_PATH='--reference=/data001/vc.integrator/mirror'
+    local url_mirror=${mirror_PATH}/${revision}
 
     #url handle with replication server
     local file_info=$(mktemp)
-    if [ -z "${url}" ] || [ "${url}" != "${url/lamp/}" ]; then 
-        bar outline 'repo server info' > ${file_info}
-        findProperREPLServer ${file_info}
-        url="ssh://${REPL_SERVER}/platform/manifest.git"; 
-    fi
-    if [ -z "${reference}" ];then reference="${reference:-${path_mirror}/${revision}}"; fi
-    if [ -z "${repo_url}" ] || [ "${url}" != "${url/lamp/}" ];then repo_url='ssh://lamp.lge.com:29418/repo/git-repo.git';fi;
+    bar outline 'repo server info' > ${file_info}
+    findProperREPLServer ${file_info}
+    
+    
+    local cmd_repoinit="repo init $@ ${url_mirror}"
+    if [ -n ${url} ];                 then cmd_repoinit="${cmd_repoinit} -u ${url}"; 
+        else cmd_repoinit="${cmd_repoinit} -u ssh://${REPL_SERVER}/platform/manifest.git"; fi
+    if [[ "${revision}" =~ "lamp" ]]; then cmd_repoinit="${cmd_repoinit} --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git"; 
+        else cmd_repoinit="${cmd_repoinit} -b ${revision}"; fi
+    if [ -n ${manifest} ];            then cmd_repoinit="${cmd_repoinit} -m ${manifest}" ;fi    
+    if [ -n ${current} ];             then cmd_repoinit="${cmd_repoinit} -c ${current}"  ;fi    
 
-    cmd_repoinit="repo init ${url:+-u ${url}} ${revision:+-b ${revision}} ${manifest:+-m ${manifest}} ${platform:+-p ${platform}} ${reference:+--reference=${reference}} ${depth:+--depth=${depth}} ${repo_url:+--repo-url=${repo_url}} ${extra} $@"
 
+    read -p "${cmd_repoinit}: "    
     #make final repo init cmd
-    bar outline "executed command:" >> ${file_info}
+    bar outline >> ${file_info}
+    printf "generated full command:\n" >> ${file_info}
     printf "${cmd_repoinit}\n" >> ${file_info}
-
+    
     #execute cmd
     time runRepoInitcheckError ${cmd_repoinit}
-    
-    grep -nEe "(fatal|fail|error)" ${file_error} >/dev/null
-    if [ $? -eq 0 ]; then 
-        bar outline "check error">> ${file_info}
-        err "${file_error}" >> ${file_info}
-    fi
+    bar outline >> ${file_info}
+    printf "${red}error logfile: ${file_error} ${NCOL}\n" >> ${file_info}
+    bar outline >> ${file_info}
     
     #show repo info
-    bar outline >> ${file_info}
     cat ${file_info}; rm -f ${file_info}
     return
 }
 
 
 
-function showManifestFile(){
-## ---------------------------------------------------------------------------
-# read file and print line "include" keyword
-# $1 manifest file name
-# $2 treedepth to display sub manifest
-    local file 
-    local path='|--|--|--|--|--'
-    local treedepth=${2:-0}
-
-    (( treedepth=treedepth+3 ))
-    cat $1 | sed -n 's/.*include name="\(.*\)".*/\1/p' | while read -r file; do
-        if [ -n "${file}" ];then   
-            printf "%s${file} %s\n" "${path::${treedepth}}"
-            showManifestFile ${file} ${treedepth}
-        fi
-        
-    done
-    (( treedepth=treedepth-3 ))
-}
-
- 
-
-function getRepoInfo(){
-## ---------------------------------------------------------------------------
-# print information of repo
-# $1 manifests file (default is current manifests)
-
-    oldIFS=${IFS}; IFS=''; 
-    getRepoCMD show
-    
-    local manifest=${1:-${FILE_MANI}}
-    bar inline "manifests: ${manifest}"
-    showManifestFile ${manifest}
-    
-    IFS=${oldIFS}
-}
-
-
-
 function handleMenu(){
 ## ---------------------------------------------------------------------------
-# show ui menu for this script
 printf ${green}
 cat << PREFACE
 ==============================================================
  the menu for repo tools
  -------------------------------------------------------------
- supported command: ex) rep info
-     info) info
-     download) init sync auto
+ account=$account, user_id=$(id -u ${account}), group_id=$user_id
+ home_dir=${home_dir}"
+ -------------------------------------------------------------
+ supported command: ex) dock list
+     info) list, images, images --all, ps, ps --all
+     image) build, hello
+     run) start, run, exec, debug
+     delete) stop, rm, rmi, remove, clean
 ==============================================================
 PREFACE
 printf ${NCOL}
 
     local COLUMNS=60
-    PS3=$'\e[00;35m=== Please input command! [enter:menu, number:choice, ctrl+c:exit] === : \e[0m'
-    select CHOICE in info init sync 
+    PS3=$'\e[00;35m=== Please input command! [Enter:menu, Ctrl+c:exit] === : \e[0m'
+    select CHOICE in list images ps build hello start run exec stop remove clean debug find pull push
     do
         handleCommand $CHOICE
     done
 }
 
 
+
+function showManifestFile(){
+## ---------------------------------------------------------------------------
+    local file 
+    local path='|--|--|--|--|--'
+    local depth=0
+
+    (( depth=depth+3 ))
+    cat $1 | sed -n 's/.*include name="\(.*\)".*/\1/p' | while read -r file; do
+        if [ -n "${file}" ];then   
+            printf "%s${file}\n" "${path::${depth}}"
+            showManifestFile ${file} ${depth}
+        fi
+        
+    done
+    (( depth=depth-3 ))
+}
+
  
+ 
+function getRepoINFO(){
+## ---------------------------------------------------------------------------
+    oldIFS=${IFS}; IFS=''; 
+    
+    getRepoCMD show
+    printToFILE no 
+    showManifestFile ${1:-${FILE_MANI}}
+    printToFILE no 
+    IFS=${oldIFS}
+}
+
+
+
 function handleCommand(){
 ## ---------------------------------------------------------------------------
-# main handler for this script
-# $1 command
-
 local ret=0
     case $1 in
         init) repoInit "${@:2}"
-            printf "${YELLOW}To RUN next command: ${NCOL}\n"
+            printf "${YELLOW}run next command: ${NCOL}\n"
             runRepoSynccheckError                       ;;
         sync) runRepoSynccheckError                     ;;
-        info) getRepoInfo
-              bar inline "repo info"
+        info) getRepoINFO
               repo info                                 ;;
+        path) findFileLocation .repo/manifests 5        ;;
         "") handleMenu "${@}"                           ;;
         *) repo "${@}"
           return $ret                                   ;;
diff --git a/tools/rep2 b/tools/rep2
--- a/tools/rep2
+++ b/tools/rep2
@@ -12,6 +12,7 @@ source ${SCRIPT_DIR}/prelibrary
 #user setting
 account=vc.integrator
 mirror="/data001/${account}"/mirror
+file_error=~/.repoconfig/repo.error
 path_mirror=/data001/vc.integrator/mirror
 rm -f ${file_error}
 
@@ -62,10 +63,11 @@ function runRepoInitcheckError(){
     echo "\$ $@"  
     "$@" 2> >(tee -a ${file_error})
     #"$@" | tee -a ${file_error}
-
-    if [ $? -ne 0 ];then runSSHcheckError ssh -p vc.integrator@vgit.lge.com:29430;fi
-
-    
+    case $? in
+     0) ;;
+     1) echo Generic error, usually because invalid command line options or malformed configuration;;
+     2) echo Connection failed;;
+    esac
 }
  
  
@@ -133,7 +135,7 @@ function getRepoCMD(){
 # get repo command from exising repo project
 # $1 show repo command (default: save info to each variable such as REMOTE_URL, BRANCH_REPO, ...)
     findFileLocation .repo/manifests 5
-    if [ -d "${REPO_PATH}" ];then cd ${REPO_PATH};else err "you are not in repo project";exit;fi
+    if [ -d "${REPO_PATH}" ];then cd ${REPO_PATH};else error "you are not in repo project";exit;fi
     
     local count file_tempa file_tempb 
         
@@ -218,7 +220,7 @@ function repoInit(){
     #option handle
     local url revision manifest platform reference depth repo_url extra
     if ! options=$(getopt -l reference:,depth:,repo-url:,no-clone-bundle,partial-clone,no-tags,mirror -o b:m:p:u: -- "$@")
-    then err 'please check "repo init --help"'; exit 1; fi
+    then error 'please check "repo init --help"'; exit 1; fi
 
     #reset legacy positional parameter except $options
     eval set -- "$options"
@@ -242,44 +244,151 @@ function repoInit(){
 
     #revision handle
     if [ -z "${revision}" ];then
-        printf "usage: rep init -b [branch] [-m manifest.xml] \n";
+        printf "usage: vrepo init -b [branch] [-m manifest.xml] \n";
         bar outline         
-        printf "ex: rep init -b lampauto_s_release -m all.xml \n";
-        printf "ex: rep init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1 \n";
-        printf "ex: rep init -u ssh://lampgd1.lge.com:29418/platform/manifest.git -b lampauto_r_release \n -m lampauto/lampauto-gm-recent.xml --reference=/data001/vc.integrator/mirror/lampauto_r_release/ \n --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git \n";
+        printf "ex: vrepo init -b lampauto_s_release -m all.xml \n";
+        printf "ex: vrepo init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1 \n";
+        printf "ex: vrepo init -u ssh://lampgd1.lge.com:29418/platform/manifest.git -b lampauto_r_release \n -m lampauto/lampauto-gm-recent.xml --reference=/data001/vc.integrator/mirror/lampauto_r_release/ \n --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git \n";
         exit
     fi
 
     #url handle with replication server
     local file_info=$(mktemp)
-    if [ -z "${url}" ] || [ "${url}" != "${url/lamp/}" ]; then 
-        bar outline 'repo server info' > ${file_info}
-        findProperREPLServer ${file_info}
-        url="ssh://${REPL_SERVER}/platform/manifest.git"; 
-    fi
+    bar outline 'repo server info' > ${file_info}
+    findProperREPLServer ${file_info}
+    if [ -z "${url}" ] || [ "${url}" != "${url/lamp/}" ]; then url="ssh://${REPL_SERVER}/platform/manifest.git"; fi
     if [ -z "${reference}" ];then reference="${reference:-${path_mirror}/${revision}}"; fi
     if [ -z "${repo_url}" ] || [ "${url}" != "${url/lamp/}" ];then repo_url='ssh://lamp.lge.com:29418/repo/git-repo.git';fi;
 
     cmd_repoinit="repo init ${url:+-u ${url}} ${revision:+-b ${revision}} ${manifest:+-m ${manifest}} ${platform:+-p ${platform}} ${reference:+--reference=${reference}} ${depth:+--depth=${depth}} ${repo_url:+--repo-url=${repo_url}} ${extra} $@"
 
     #make final repo init cmd
-    bar outline "executed command:" >> ${file_info}
-    printf "${cmd_repoinit}\n" >> ${file_info}
-
+    bar outline "generated full command:\n" >> ${file_info}
+    printf "${cmd_repoinit}" >> ${file_info}
+    
     #execute cmd
     time runRepoInitcheckError ${cmd_repoinit}
-    
-    grep -nEe "(fatal|fail|error)" ${file_error} >/dev/null
-    if [ $? -eq 0 ]; then 
-        bar outline "check error">> ${file_info}
-        err "${file_error}" >> ${file_info}
-    fi
+    bar outline >> ${file_info}
+    printf "${red}error logfile: ${file_error} ${NCOL}\n" >> ${file_info}
+    bar outline >> ${file_info}
     
     #show repo info
-    bar outline >> ${file_info}
     cat ${file_info}; rm -f ${file_info}
     return
 }
+
+function repoInit_(){
+## ---------------------------------------------------------------------------
+# repo init helper
+# $1 short repo init command
+    #option handle
+    local repo_URL url_repl url revision manifest opt left
+    while getopts m:b:u:c opt 2> /dev/null; do
+       case $opt in
+          u) url=$OPTARG;;
+          b) revision=$OPTARG;;
+          m) manifest=$OPTARG
+            read -p [$manifest]
+          ;; 
+          c) current=$OPTARG;;
+          *) left=${left} $OPTARG;;
+       esac
+    done
+
+    #revision handle
+    if [ -z "${revision}" ]; then 
+        printf "usage: vrepo init -b [branch] [-m manifest.xml] \n";
+        bar outline         
+        printf "ex: vrepo init -b lampauto_s_release -m all.xml \n";
+        printf "ex: vrepo init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1 \n";
+        printf "ex: vrepo init -u ssh://lampgd1.lge.com:29418/platform/manifest.git -b lampauto_r_release \n -m lampauto/lampauto-gm-recent.xml --reference=/data001/vc.integrator/mirror/lampauto_r_release/ \n --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git \n";
+        echo "${revision}"
+        exit
+    fi
+    
+    local path_mirror='--reference=/data001/vc.integrator/mirror'
+    local url_mirror=${path_mirror}/${revision}
+
+    #url handle with replication server
+    local file_info=$(mktemp)
+    bar outline 'repo server info' > ${file_info}
+    findProperREPLServer ${file_info}
+    
+    
+    local cmd_repoinit="repo init $@ ${url_mirror}"
+    if [ -z "${url}" ];               then cmd_repoinit="${cmd_repoinit} -u ssh://${REPL_SERVER}/platform/manifest.git"; fi
+    if [[ "${revision}" =~ "lamp" ]]; then 
+        cmd_repoinit="${cmd_repoinit} --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git"; 
+    else 
+        cmd_repoinit="${cmd_repoinit}"; 
+    fi
+
+    if [ -n "${current}" ];           then cmd_repoinit="${cmd_repoinit} -c ${current}"  ;fi    
+
+    #make final repo init cmd
+    bar outline >> ${file_info}
+    printf "generated full command:\n" >> ${file_info}
+    printf "${cmd_repoinit}\n" >> ${file_info}
+    
+    #execute cmd
+    time runRepoInitcheckError ${cmd_repoinit}
+    bar outline >> ${file_info}
+    printf "${red}error logfile: ${file_error} ${NCOL}\n" >> ${file_info}
+    bar outline >> ${file_info}
+    
+    #show repo info
+    cat ${file_info}; rm -f ${file_info}
+    return
+}
+
+function repoInit__(){
+## ---------------------------------------------------------------------------
+# repo init helper
+# $1 short repo init command
+    if ! options=$(getopt -o u:b:m:cp: -l repo-url:,mirror:,reference:,depth:,no-tags,no-clone-bundle,partial-clone -- "$@")
+    then
+        echo "ERROR: print usage"
+        exit 1
+    fi
+
+    #reset legacy positional parameter except $options
+    eval set -- $options
+    while true; do
+        case "$1" in
+            -u|--manifest-url) 
+                echo >&2 "$1 was triggered!, OPTARG: $2"
+                shift 2;;
+            -b|--manifest-branch)    
+                echo >&2 "$1 was triggered!, OPTARG: $2"
+                shift 2;; #when option has sub param, should shift 2
+            -m|--manifest-name)
+                echo >&2 "$1 was triggered!, OPTARG: $2"
+                shift 2;;
+            -c|--current-branch)
+                echo >&2 "$1 was triggered!, OPTARG: $2"
+                shift ;; 
+            --mirror|--reference|--depth|--repo-url)
+                echo >&2 "$1 was triggered!, OPTARG: $2"
+                shift 2;;
+            --no-clone-bundle|--partial-clone|--no-tags)
+                echo >&2 "$1 was triggered!"
+                shift;;
+            --)           
+                shift 
+                break ;;
+            *)           
+                shift 
+                break ;;               
+        esac
+    done
+
+    echo -------------------- leftover
+    echo "$@"
+
+    exit
+}
+
+
 
 
 
@@ -330,7 +439,7 @@ cat << PREFACE
 ==============================================================
  the menu for repo tools
  -------------------------------------------------------------
- supported command: ex) rep info
+ supported command: ex) vrepo info
      info) info
      download) init sync auto
 ==============================================================
