change repp.csv from json

diff --git a/tools/repp b/tools/repp
--- a/tools/repp
+++ b/tools/repp
@@ -532,18 +532,79 @@ EOF
 
 
 
+function reppmanigen(){
+## ---------------------------------------------------------------------------
+# find git repository with path and project name with regexp
+# $1 path or project
+# usage: reppfind [path|project]
+
+    if (( "$(reppversion ver)" < 230 )); then
+        warn "run 'repp version toggle' to update repo latest"
+        return 1;
+    fi
+
+    local mani_out=()
+    repo manifest -r --json -o ${REPPFILE_JSON}
+    readarray -d'|' -t itemdefault < <(cat  ${REPPFILE_JSON} |jq -j '.default|.revision,"|",.groups,"|",.remote,"|",.upstream,"|",."dest-branch","|",.name,"|",.path,"\n"')
+    #declare -p itemdefault
+
+    readarray -t multiline < <(cat  ${REPPFILE_JSON}|jq -jr '.project[]|.revision,"|",.groups,"|",.remote,"|",.upstream,"|",."dest-branch","|",.name,"|",.path,"|\n"')
+    for line in "${multiline[@]}"; do
+        ##read one item from line by '|'
+        local index=0 itemtemp
+        local lineout=''
+        $DEBUG ${line}
+        while read -d'|' item; do
+            $DEBUG "[%s] %s\n" "${index}" "${item}" 
+            case ${item} in
+                null)           item=${itemdefault[index]}
+                ;; *)           :
+            esac
+            case ${index} in
+                  0)            item=${item:0:6};  #revision, truncate digit to 6
+                                [ "${item}" = "null" ] && { err "${lineout}[${index}]"; return 1; }
+                ;;1)            [ "${item}" = "null" ] && item="all,default" #group
+                                [ "${item}" = "null" ] && return 1
+                ;;2|5|6)        if [ "${item}" = "null" ];then err "${lineout}[${index}]"; return 1; fi
+                                [ "${item}" = "null" ] && return 1
+                ;;3)            itemtemp=${item} #upstream(read), if null, revison is used 
+                ;;4)            if [ "${item}" = "${itemtemp}" ]; #dest-branch, compare to upstream
+                                then item=''; #good 
+                                else item=''; warn "pull/push address is different (${line})"; #need to check
+                                fi
+            esac            
+            index=$(( ++index ))
+            lineout+="${item:+"${item}|"}"
+        done <<< "${line}"
+        $DEBUG "%s\n" "${lineout}"
+        mani_out+=(${lineout})
+    done
+    #declare -p mani_out
+    local prnmsg='%6.6s|%12.12s|%8.8s|%-32.32s|%-74.74s|%.80s'
+    printf "${prnmsg}\n" ${mani_out[*]//|/ } >  ${REPPFILE_CSV}
+
+    #cat ${REPPFILE_JSON}|jq -cC '.project[]|{groups,remote,upstream,"dest-branch",revision,name,path}'
+    #cat resultr.json|jq -jr '.project[]|.groups,"|",.remote,"|",.upstream,"|",."dest-branch","|",.revision,"|",.name,"|",.path,"\n"'
+    #cat resultr.json|jq -jr '.project[]|.groups," ",.remote," ",.upstream," ",."dest-branch"," ",.revision," ",.name," ",.path,"\n"'
+    #cat ${REPPFILE_JSON}|jq -cM '.project[]|{groups,remote,upstream,"dest-branch",revision,name,path}'|tr -d '"'
+}
+
+
+
 function reppfind(){
 ## ---------------------------------------------------------------------------
 # find git repository with path and project name with regexp
 # $1 path or project
 # usage: reppfind [path|project]
     local cmd="$1"
-    local prnmsg='%6.6s %8.8s %-32.32s %-74.74s %.80s'
+    local prnmsg='%6.6s|%12.12s|%8.8s|%-32.32s|%-74.74s|%.80s'
 
     if [ -f "${REPPFILE_CSV}" ];
     then info "reuse generated file [\${REPPFILE_CSV}] or you can remove and retry this";
-    else repo forall -j1 -c 'prnmsg="%6.6s|%8.8s|%-32.32s|%-74.74s|%.80s";
-    printf "${prnmsg}\n" "${REPO_LREV}" "${REPO_REMOTE}" "${REPO_RREV}" "${REPO_PROJECT}" "${REPO_PATH}"' > ${REPPFILE_CSV} 2>/dev/null 
+    else 
+    reppmanigen
+    repo forall -j1 -c 'prnmsg="%6.6s|%12.12s|%8.8s|%-32.32s|%-74.74s|%.80s"
+    printf "${prnmsg}\n" "${REPO_LREV}" "all,default" "${REPO_REMOTE}" "${REPO_RREV}" "${REPO_PROJECT}" "${REPO_PATH}"' > ${REPPFILE_TXT} 2>/dev/null 
     fi
 
     case ${cmd} in
@@ -556,6 +617,7 @@ function reppfind(){
 		   ex) repp find |grep -v vendor/qct       # list git info not containing 'vendor/qct'
 		   ex) cat \${REPPFILE_CSV}                 # cat output file
 		usage) repp find @rev                      # print rev colume for all repo
+		usage) repp find @group                    # print group colume for all repo
 		usage) repp find @remote                   # print project colume for all repo
 		usage) repp find @branch                   # print branch colume for all repo
 		usage) repp find @project                  # print project colume for all repo
@@ -563,17 +625,18 @@ function reppfind(){
 		   ex) repp find @project |grep meta       # print project colume containing 'meta'
 EOF
     ;; @rev)      clog "<REPO_LREV>";    awk -v FS="|" '{print $1}' ${REPPFILE_CSV} |pCount
-    ;; @remote)   clog "<REPO_REMOTE>";  awk -v FS="|" '{print $2}' ${REPPFILE_CSV} |sort |uniq |pCount
-    ;; @branch)   clog "<REPO_RREV>";    awk -v FS="|" '{print $3}' ${REPPFILE_CSV} |sort |uniq |pCount
-    ;; @project)  clog "<REPO_PROJECT>"; awk -v FS="|" '{print $4}' ${REPPFILE_CSV} |sort |pCount
-    ;; @path)     clog "<REPO_PATH>";    awk -v FS="|" '{print $5}' ${REPPFILE_CSV} |sort |pCount
-    ;; '')        printf "\e[1;33m${prnmsg} \e[0m\n" "REPO_LREV" "REPO_REMOTE" "REPO_RREV" "REPO_PROJECT" "REPO_PATH"
+    ;; @group)    clog "<REPO_GROUP>";   awk -v FS="|" '{print $2}' ${REPPFILE_CSV} |sort |uniq |pCount
+    ;; @remote)   clog "<REPO_REMOTE>";  awk -v FS="|" '{print $3}' ${REPPFILE_CSV} |sort |uniq |pCount
+    ;; @branch)   clog "<REPO_RREV>";    awk -v FS="|" '{print $4}' ${REPPFILE_CSV} |sort |uniq |pCount
+    ;; @project)  clog "<REPO_PROJECT>"; awk -v FS="|" '{print $5}' ${REPPFILE_CSV} |sort |pCount
+    ;; @path)     clog "<REPO_PATH>";    awk -v FS="|" '{print $6}' ${REPPFILE_CSV} |sort |pCount
+    ;; '')        printf "\e[1;33m${prnmsg} \e[0m\n" "REPO_LREV" "REPO_GROUP" "REPO_REMOTE" "REPO_RREV" "REPO_PROJECT" "REPO_PATH"
                   cat ${REPPFILE_CSV} |pCount
                   printf "\n\n"
                   info "Above \${REPPFILE_CSV} is generated, all repository info is save: ${REPPFILE_CSV}"
                   clog "\${REPPFILE_CSV}" "this file can opened by excel menu [data> text> select file> file open wizard], or reformatted by [data>text to columns> select delimter'|'> finish]"
                   clog "to see help: " "repp find help"
-    ;; *)         printf "\e[1;33m${prnmsg} \e[0m\n" "REPO_LREV" "REPO_REMOTE" "REPO_RREV" "REPO_PROJECT" "REPO_PATH"
+    ;; *)         printf "\e[1;33m${prnmsg} \e[0m\n" "REPO_LREV" "REPO_GROUP" "REPO_REMOTE" "REPO_RREV" "REPO_PROJECT" "REPO_PATH"
                   cat ${REPPFILE_CSV} | grep -i --color=always ${cmd} |pCount
     esac
 }
@@ -837,13 +900,35 @@ EOF
 
 function reppvertoggle(){
 ## ---------------------------------------------------------------------------
-if [ -d "${REPP_PATH%/*}/__repo" ]; 
+local repo_executor=${proFILEdir}/bin/_repo
+local repo_launcher_backup=${REPP_PATH%/*}/__repo
+local repo_launcher=${REPP_PATH%/*}/repo
+
+## update repo newest
+if [ -d "${repo_executor}" ];
+then
+    git -C ${proFILEdir}/bin/_repo pull
+else
+    git clone https://gerrit.googlesource.com/git-repo -b stable ${repo_executor}
+fi
+
+## back or restore
+if [ -d "${repo_launcher_backup}" ];
 then ## restore
-    [ -L "${REPP_PATH%/*}/repo" ] && rm -f ${REPP_PATH%/*}/repo || ( err "cannot restore, plz check"; return 1 )
-    mv ${REPP_PATH%/*}/__repo ${REPP_PATH%/*}/repo
+    [ -L "${repo_launcher}" ] && rm -f ${repo_launcher} || ( err "cannot restore, plz check"; return 1 )
+    mv ${repo_launcher_backup} ${repo_launcher}
+    
+    ## restore PATH
+    [[ -v PATH_OLD ]] && PATH=${PATH_OLD}
+    
 else ## backup & change
-    mv ${REPP_PATH%/*}/repo ${REPP_PATH%/*}/__repo
-    ln -s ${proFILEdir}/bin/_repo ${REPP_PATH%/*}/repo
+    mv ${repo_launcher} ${repo_launcher_backup}
+    ln -s ${repo_executor} ${repo_launcher}
+    
+    ## add path for priority
+    ## if variable is not defined, backup PATH, ban re-enterd
+    [[ -v PATH_OLD ]] || PATH_OLD=$PATH
+    PATH=${repo_launcher}:$PATH
 fi
 }
 
@@ -854,7 +939,7 @@ function reppversion(){
 # print information of repo
 # $1 manifests file (default is current manifests)
     local file_log=$(mktemp)
-    python3  $(which repo) --version > ${file_log}
+    python3 $(which repo) --version > ${file_log}
     
     local VER cmd="$1"
     case $cmd in
@@ -862,10 +947,10 @@ function reppversion(){
 			usage) repp version toggle         # change repo version newest & restore
 			usage) repp version                # reset all repository to original revision
 EOF
-        ;; toggle) reppvertoggle; return 0;
         ;;    ver) ## only 3digit length version code is valid to compare old version
                    VER=$(cat ${file_log} | grep "repo version"  |tr -dc '[:digit:]')   
                    echo ${VER:0:3} && return 0
+        ;; toggle) reppvertoggle; return 0
     esac
     #if VER is not integer, in case of error
     [[ ${VER} != ?(-)+([0-9]) ]] && VER=000
@@ -1148,6 +1233,8 @@ function repp_initvar(){
     REPPFILE_STATUS=${REPP_ROOT}/repp.status
     REPPFILE_COMMIT=${REPP_ROOT}/repp.commit
     REPPFILE_CSV=${REPP_ROOT}/repp.csv
+    REPPFILE_TXT=${REPP_ROOT}/repp.txt
+    REPPFILE_JSON=${REPP_ROOT}/repp.json
     REPPFILE_XML=repp.xml
 
     if [[ $ret -eq 1 ]]; then
