change serverinfo to revvserver

diff --git a/tools/repp b/tools/repp
--- a/tools/repp
+++ b/tools/repp
@@ -509,8 +509,7 @@ function reppinfo(){
     clog "number of repositories: " $REPP_COUNT
     clog "duplicated repositories:" ""
     awk -v 'FS=|' '{print $7}' ${REPPFILE_CSV} |sort|uniq -dc |pCount
-    sleep 1
-    read -p "Press enter to continue to show extra information(generated by 'repp mani db') ... "
+    read -t 2 -p "Press Ctrl+C not to see extra information(generated by 'repp mani db') ... "
 
     ##manifest에 기록된 remote정보를 보여준다.
     bar inline "remotes & review sites"
@@ -714,15 +713,15 @@ function reppmanidb(){
     ## get <default> from json
     readarray -d'|' -t item_default < <(cat  ${REPPFILE_JSON} |jq -j '.default|.revision,"|",.groups,"|",.remote,"|",.upstream,"|",."dest-branch","|",.name,"|",.path,"|"')
     ## get <remote.alias> from json
-    readarray -t items_alias < <(cat  ${REPPFILE_JSON} |jq -jr '.remote[]|select(.alias!=null)|.name,"=",.alias')
     #declare -p items_alias
+    readarray -t items_alias < <(cat  ${REPPFILE_JSON} |jq -jr '.remote[]|select(.alias!=null)|.name,"=",.alias')
     readarray -t items_project < <(cat  ${REPPFILE_JSON}|jq -jr '.project[]|.revision,"|",.groups,"|",.remote,"|",.upstream,"|",."dest-branch","|",.name,"|",.path,"|\n"'|sort)
 
     ## save to array
     local mani_out=()
     printf "takes time at first, creating .repp dir & DB files by analysing manifest\n\n"
     ## read one line from items_project array
-    local line
+    local line count=0
     for line in "${items_project[@]}"; do
         $DEBUG ${line}
         ##read one item from line by '|'
@@ -736,6 +735,7 @@ function reppmanidb(){
             ##preprocessor, override value from default
             [ "${item}" = "null" ] && item=${item_default[index]};
 
+            ## 칼럼순서대로 1:revision, 2:group, 3:remote, 4:upstream, 5:dest_branch, 6:rrev, 7:project, 8:path
             ##process item according to index
             case ${index} in
                 #revision: if ok, truncate digit to 6
@@ -743,10 +743,11 @@ function reppmanidb(){
                 #group : assign default value, if value is not defined
                 ;;1)   [ "${item}" = "null" ] && item="all,default"
                 #remote: replace alias by original name
-                ;;2)   [ "${item}" = "null" ] && warn "${lineout}[${index}] is null"
+                ;;2)   [ "${item}" = "null" ] && warn "${lineout}[${index}] remote is null"
                        for alias in ${items_alias[@]};do [ "${item}" = "${alias%=*}" ] && item="${alias#*=}";done
                 #name, path: if null stop, it is mandatory
-                ;;5|6) [ "${item}" = "null" ] && { (($index == 5)) && err "${lineout}[name] is null" || err "${lineout}[path] is null"; }
+                ;;5) [ "${item}" = "null" ] && warn "${lineout} name is null"
+                ;;6) [ "${item}" = "null" ] && warn "${lineout} path is null"
                 #upstream:
                 ;;3)   itemrrev=${item}
                 #dest-branch: decide revision from upstream
@@ -758,7 +759,9 @@ function reppmanidb(){
             index=$(( ++index ))
             lineout+="${item:+"${item}|"}"
         done <<< "${line}"
-        $DEBUG "%s\n" "${lineout}"
+        count=$(( ++count ))
+        #(( ${count} > 10 )) && break
+        #$DEBUG "%s\n" "${lineout}"
         #printf "%s\n" "${lineout}"
         #lineout+="${itemrrev}"
         mani_out+=(${lineout})
@@ -1508,7 +1511,8 @@ function repp_initvar(){
     ## set variable REPP if manifest dir exists
     if [ -d "${REPP_PATH}" ];then
         pushd ${REPP_PATH}
-        REPP_REMOTE=$(getServer $(git remote -v |grep fetch | grep -oP '(?<=:)[0-9]+(?=/)') remote)
+        #REPP_REMOTE=$(getServer $(git remote -v |grep fetch | grep -oP '(?<=:)[0-9]+(?=/)') remote)
+        REPP_REMOTE=$(repo manifest -r --json 2>/dev/null |jq -r '.default.remote')
         #REPP_PROJECT=$(git remote -v |grep fetch | sed -E 's#.*[0-9]+(.*).git.*$#\1#')
         #REPP_PROJECT=$(git config --get-regexp remote.*.url  |head -1|cut -d' ' -f2)
         REPP_PROJECT=$(git config --get-regexp remote.* |grep -Ee "(projectname|url)" |head -1|grep -Po '\w/\K.\w+[^?]+')
@@ -1605,7 +1609,7 @@ function revv_initvar(){
 
     if (( 40 > ${#key} )); then
         warn "if problem continue, check gerrit http key value in [~/.key_server] \n
-        you can generate file [.key_server] : cmd[serverinfo gen] and add access key"
+        you can generate file [.key_server] : cmd[revvserver gen] and add access key"
         ret=1
     fi
 
@@ -1661,7 +1665,7 @@ function gittsshcmd(){
 EOF
 
     ;; checkserver)
-        if [ -z "${server}" ] || [ -z "${port}" ] ; then info "usage) revv server vgit.lge.com 29999"; return 1;fi
+        if [ -z "${server}" ] || [ -z "${port}" ] ; then info "usage) revv server status vgit.lge.com 29999"; return 1;fi
         ping $server -s 1016 -c 4 -A
         printf "${yellow}--------------------------------------------------------------------------------------\n${NCOL}"
         if [ $? -ne 0 ]; then continue; fi
@@ -2132,6 +2136,114 @@ EOF
 
 
 ## revv ======================================================================================================================
+function  getServer() {
+## ---------------------------------------------------------------------------
+## return remote (gerrit server) info as a various type
+## format: getServer [29420|na|vgit|lamp|review] [port|http|sub|domain|subdomain|path|url|remote|debug]
+## exception: vgitxxx lampxxx will return only postfix after delimter _
+##            aaa-bbb같이 -를 포함하는 sub은 -앞의 string(aaa)만 사용한다.
+
+    local key=$1
+    local _item=$(revvserver de $key |awk -F '|' '{print $2}')
+    local return_type=$2
+
+    case ${return_type} in                                                                    # return value
+            http)    echo "${_item%:*}"                                                       # http://vgit.lge.com/na
+    ;;      port)    echo "${_item##*:}"                                                      # 29420
+    #;;       sub)    echo "${_item#*://}"| awk -F[./:] '{sub(/-.*/,"",$1);print $1}'          # vgit
+    ;;       sub)    echo "${_item#*://}"| awk -F[./:] '{print $1}'          # vgit
+    ;;    domain)    echo "${_item#*://}"| awk -F[./:] '{print $2"."$3}'                      # lge.com
+    ;; subdomain)    echo "${_item#*://}"| awk -F[./:] '{print $1"."$2"."$3}'                 # vgit.lge.com
+    ;;      path)    echo "${_item#*://}"| awk -F[./:] '{print $4}'                           # na
+    ;;       url)    echo "${_item#*://}"| awk -F[./:] '{$4="/"$4;gsub(/\/none_.*/,"",$4);print $1"."$2"."$3$4}'            # vgit.lge.com/na
+    ;;    remote)    echo "${_item#*://}"| awk -F[./:] '{print $1"_"$4}'                      # vgit_na
+    ;;      pass)    revvserver de $key  | awk -F '[[:space:]]*\\|'  '{print $4}'                           # N4lIA0SoQAoUfxlmCZudjNA12344
+    ;;      user)    revvserver de $key  | awk -F '[[:space:]]*\\|'  '{print $3}'                           # vc.integrator
+    ;;     debug)    echo "${_item}"                                                          # http://vgit.lge.com/na:29420
+    ;;         *)    echo "NULL";                                                             # vgit.lge.com/na:29420
+    esac
+
+}
+
+
+function revvserver(){
+## ---------------------------------------------------------------------------
+# encoding as variable: code env <keyname> <key>
+# encoding as file: code en <keyfile> <key>
+# decode de <keyfile>
+local temp temp_var
+local cmd=$1 tag=$2 key=$3
+    case $cmd in
+       gen) #default server 접속정보 파일인 ~/.key_server를 생성한다.
+            clog ".key_server" "is generated, \nplease add your server info with http key from: https://gerrit.url.com/settings/#HTTPCredentials\n"
+        cat <<-EOF  >.key_server
+			REMOTE,KEY   |URL to GERRIT                                         |ACCOUNT         |HTTP KEY
+			vgit_na      |http://vgit.lge.com/na:29420                          |vc.integrator   |ex)N4lIA0SoQAoUfxlmCZudjNA1
+			vgit_eu      |http://vgit.lge.com/eu:29430                          |vc.integrator   |~~~
+			vgit_as      |http://vgit.lge.com/as:29440                          |vc.integrator   |~~~
+			vgit_adas    |http://vgit.lge.com/adas:29550                        |vc.integrator   |
+			devops_test  |http://vgit.lge.com/devops_test:29999                 |vc.integrator   |
+			review       |http://lamp.lge.com/review:29418                      |vc.integrator   |
+EOF
+        cat .key_server
+
+    ;;  en) #~/.key_server.en 로 암호화한다.
+            if [ -f $HOME/.key_server ]; then
+                clog "$HOME/.key_server will be converted to $HOME/.key_server.en with encrypting"
+                cat $HOME/.key_server | openssl enc -base64 -e -aes-256-cbc -nosalt -pbkdf2  -pass pass:garbageKey > $HOME/.key_server.en
+                rm -f $HOME/.key_server
+            else
+                clog "$HOME/.key_server.en" "could be updated by '$FUNCNAME editing' [$HOME/.key_server]"
+                err "You must create server connection info, use '$FUNCNAME gen'"; return 1
+            fi
+
+    ;;edit) #~/.key_server.en으로 부터 ~/.key_server를 생성하여 편집할수 있게 해준다.
+            cat $HOME/.key_server.en | openssl enc -base64 -d -aes-256-cbc -nosalt -pbkdf2 -pass pass:garbageKey >$HOME/.key_server
+            clog "$HOME/.key_server" "is decrypted from $HOME/.key_server.en"
+            [ -f "$HOME/.key_server" ] && cat $HOME/.key_server || { err "You must create server connection info, use '$FUNCNAME gen'"; return 1; }
+
+    ;;  de) #~/.key_server.en에서 server정보를 획득해온다.
+            if [ -f $HOME/.key_server.en ]; then
+                temp_var=$(cat $HOME/.key_server.en | openssl enc -base64 -d -aes-256-cbc -nosalt -pbkdf2 -pass pass:garbageKey |\
+                  awk -v tag="$tag" -F '[[:space:]]*\\|' '$1 == tag{print $0}')
+                if [ -n "$temp_var" ];then
+                    echo $temp_var && return 0
+                else temp_var=$(cat $HOME/.key_server.en | openssl enc -base64 -d -aes-256-cbc -nosalt -pbkdf2 -pass pass:garbageKey |\
+                  awk -v tag="$tag" -F '[[:space:]]*\\|' '$2 ~ tag && !found {print $0; found=1}')
+                    echo $temp_var && return 0
+                fi
+
+                err "matched http key is not existed or incorrect!";
+                clog "guide" "run '$FUNCNAME edit' and edit proper server info in .key_server"
+                return  1;
+            else
+                err "You must create server connection info, use '$FUNCNAME gen'"; return 1
+            fi
+
+    ;;debug) #getServer 함수 test용으로 모든 format대로 제대로 출력하는지 확인할수 있다.
+            test_getServer test
+    ;;help) cat <<- 'EOF'
+			usage) revv server <cmd> <option>
+
+			guide) example cmds REPO_SCRIPT column in reppscript.csv
+			revv server  gen             #generate template .key_server file for easy creation
+			revv server   en             #after update .key_server, encrypt it to .key_server.en
+			revv server edit             #encrypted .key_server.en will be decryped to .key_server to edit
+			revv server   de vgit_na     #search vgit_na server and get info of it from .key_server.en
+			revv server show             #show current server info from .key_server.en
+			revv server debug            #check all formats of getServer api
+EOF
+    ;;show|*)  #현재 .key_server파일을 보여준다.
+            [ ! -f $HOME/.key_server.en ] && err "You must create server connection info, use '$FUNCNAME gen'"
+            cat $HOME/.key_server.en | openssl enc -base64 -d -aes-256-cbc -nosalt -pbkdf2 -pass pass:garbageKey
+
+            clog "You can refer:" "'revv server help'"
+
+    esac
+}
+
+
+
 JSON_IDFY=")]}'"
 function revvcheck_server(){
 ## ---------------------------------------------------------------------------
@@ -2271,9 +2383,9 @@ function test_getServer() {
 ## check all format is well printed
 ## print remote (gerrit server) info for all supported format
 ## awk print 2nd line to last-1 line
-#serverinfo show |awk -F '|' 'NR>1{print $1}'
+#revvserver show |awk -F '|' 'NR>1{print $1}'
     local cmd=$1
-    for _item in $(serverinfo show |awk -F '|' 'NR>2 {print last} {last=$1}');do
+    for _item in $(revvserver show |awk -F '|' 'NR>2 {print last} {last=$1}');do
         if [ "$cmd" = test ]||[ "$cmd" = info ]; then revvcheck_server $_item log; fi
 
         if [ "$cmd" = test ]; then
@@ -2901,7 +3013,7 @@ EOF
 
 
 
-function revvserver(){
+function revvserverstatus(){
 ## ---------------------------------------------------------------------------
 # find replication server
 # $1 server-url
@@ -2911,7 +3023,7 @@ function revvserver(){
     local user=${2:-${USER}}
     local port=${3:-$(echo ${server_port} | grep -oP '(?<=:)[0-9]+(?=/)')}
 
-    if [ -z "${server}" ] || [ -z "${port}" ] ; then info "usage) revv server vgit.lge.com 29999"; return 1;fi
+    if [ -z "${server}" ] || [ -z "${port}" ] ; then info "usage) revv server status vgit.lge.com 29999"; return 0;fi
     ping $server -s 1016 -c 4 -A
     printf "${yellow}--------------------------------------------------------------------------------------\n${NCOL}"
     if [ $? -ne 0 ]; then continue; fi
@@ -2971,7 +3083,7 @@ local MENU=(
 "     info: shows repository info such as manifest path, repo cmd, tree of manifests, etc"
 "      cmd: list useful command from gerrit"
 "  connect: check if input account can access branch in gitproject on server"
-"   server: check delay from server or confirm the server status"
+"   server: check server list or status"
 "    debug: show variable REPO, REPP, REPPFILE, GITT variable used in script"
 "   forall: repoforal for revv branch commands"
 "     user: check if account is existed & get account info "
@@ -2991,8 +3103,8 @@ case "$1" in
      ##$1:cmd        ${@:2}:parameters
           help)                                            reppmenu help "${MENU[@]}"
     ;;      '')                                            reppmenu revv "${MENU[@]}"
+    ;;  server)  [ "$2" = "status" ] && revvserverstatus "${@:3}" || revvserver "${@:2}"
     ;;     cmd)      reppcheck_initvar reppgittrevv    &&  revvshowcmd "${@:2}"
-    ;;  server)      reppcheck_initvar gittrevv        &&  revvserver "${@:2}"
     ;; connect)      reppcheck_initvar gittrevv        &&  revvcheck_server "${@:2}"
     ;;    info)      reppcheck_initvar gittrevv        &&  revvinfo  "${@:2}"
     ;;   debug)      reppcheck_initvar gittrevv        &&  revvdebug "${@:2}"
