fix: reppmanidb for when not working repo

diff --git a/tools/repp b/tools/repp
--- a/tools/repp
+++ b/tools/repp
@@ -663,8 +663,9 @@ function reppmanidb(){
     ## generate json from manifest, #suppress all log for generation json
     [ -d ${REPP_DIR} ] || mkdir ${REPP_DIR}
     repo manifest -r --json -o ${REPPFILE_JSON}  &> /dev/null
-    if (( "$(reppversion ver 2>/dev/null)" > 220 )) && ! [ -f ${REPPFILE_JSON} ]; then
-        err "you are in mirror repo, use source repo not mirror "
+    if (( "$(reppversion ver 2>/dev/null)" > 220 )) && ! [ -s ${REPPFILE_JSON} ]; then
+        err "check if you are in mirror repo, use source repo not mirror "
+        err "or failed by manifest error, check with 'repo manifest -r --json'"
     fi
 
     ## get <default> from json
@@ -702,10 +703,10 @@ function reppmanidb(){
                 #group : assign default value, if value is not defined
                 ;;1)   [ "${item}" = "null" ] && item="all,default"
                 #remote: replace alias by original name
-                ;;2)   [[ "${item}" = "null" ]] && { err "${lineout}[${index}] is null"; }
+                ;;2)   [ "${item}" = "null" ] && warn "${lineout}[${index}] is null"
                        for alias in ${items_alias[@]};do [ "${item}" = "${alias%=*}" ] && item="${alias#*=}";done
                 #name, path: if null stop, it is mandatory
-                ;;5|6) [[ "${item}" = "null" ]] && { err "${lineout}[${index}] is null"; }
+                ;;5|6) [ "${item}" = "null" ] && { (($index == 5)) && err "${lineout}[name] is null" || err "${lineout}[path] is null"; }
                 #upstream:
                 ;;3)   itemrrev=${item}
                 #dest-branch: decide revision from upstream
@@ -721,6 +722,7 @@ function reppmanidb(){
         #lineout+="${itemrrev}"
         mani_out+=(${lineout})
     done
+
     #declare -p mani_out
     local prnmsg='%s|%12.12s|%8.8s|%-32.32s|%-74.74s|%.80s'
     printf "%s\n" "${mani_out[@]}" >  ${REPPFILE_CSV}
@@ -731,8 +733,8 @@ function reppmanidb(){
     #N_LREV=0 N_GROUP=1 N_REMOTE=2 N_UPSTREAM=3 N_DEST_BRANCH=4 N_REPO_RREV=5 N_PROJECT=6 N_PATH=7
 
     ## generate db by repo
-    { repo forall -j1 -c 'prnmsg="%s|%s|%s|%s|%s|%s|%s|%s|"
-    printf "${prnmsg}\n" "${REPO_LREV}" "all,default" "${REPO_REMOTE}" "${REPO_UPSTREAM}" "${REPO_DEST_BRANCH}" "${REPO_RREV}" "${REPO_PROJECT}" "${REPO_PATH}"'|sort > ${REPPFILE_CSV}.repo; } 2>/dev/null
+    repo forall -j1 -c 'echo "${REPO_LREV}|all,default|${REPO_REMOTE}|${REPO_UPSTREAM}|${REPO_DEST_BRANCH}|${REPO_RREV}|${REPO_PROJECT}|${REPO_PATH}"' |sort > ${REPPFILE_CSV}.repo
+    [ -s "${REPPFILE_CSV}.repo" ] || { err "repo is not working, must check"; return 1; }
     if (( "$(reppversion ver 2>/dev/null)" > 220 )) && ! [ -f ${REPPFILE_JSON} ]; then
         err "you are in mirror repo, temporary ${REPPFILE_CSV} is generated by force, it may show incorrect information"
         cp ${REPPFILE_CSV}.repo ${REPPFILE_CSV};
