reppmanidb make simple

diff --git a/tools/repp b/tools/repp
--- a/tools/repp
+++ b/tools/repp
@@ -127,19 +127,17 @@ function reppmani(){
     local str=$3
     local filter=$4
 
-    if [[ "${cmd}" != "db"     ]] &&\
-       [[ "${cmd}" != "go"     ]] &&\
-       [[ "${cmd}" != "script" ]] &&\
-       [[ ! "${PWD}" =~ "${REPP_PATH}" ]]; then
-        warn "you must move to manifest dir, path is changed automatically ${REPP_PATH}"
-        info "you can go by 'repp go mani' or 'git go mani'"
-        cd ${REPP_PATH}
-    fi
-
+    case ${cmd} in
+        info|gen|change|diff|diffcheck) if [[ ! "${PWD}" =~ "${REPP_PATH}" ]]; then
+            warn "you must move to manifest dir, path is changed automatically ${REPP_PATH}"
+            info "you can go by 'repp go mani' or 'git go mani'"
+            cd ${REPP_PATH}; fi
+        ;; *)
+    esac
 
     case ${cmd} in
-          db)   rm -f ${REPPFILE_CSV} ${REPPFILE_TXT} ${REPPFILE_JSON};
-                if  ! reppmanidb; then
+          db)   ##remove repp.csv and all related files
+                if  ! reppmanidb gen ; then
                     warn "DB is not generated well, please check error"
                     bar inline "${REPPFILE_TXT}"
                     echo "you can use this for simple use, it generated only from manifest git"
@@ -692,13 +690,15 @@ return 0
 function reppmanidb(){
 ## ---------------------------------------------------------------------------
 # find git repository with path and project name with regexp
-# $1 path or project
-# usage: reppfind [path|project]
+# $1 command
+# usage: reppmanidb
 
-    [ -f "${REPPFILE_CSV}" ] && {
-        $DEBUG "\${REPPFILE_CSV}:${REPPFILE_CSV} reused above file or you can remove and refresh repository info";
-        return 0;
-    }
+    local cmd=$1
+    case $cmd in
+        gen) if [ -d "${REPP_DIR}" ] && [[ "${REPP_DIR}" =~ ".repp" ]]; then rm -rf ${REPP_DIR}; fi
+      ;;  *) [ -f "${REPPFILE_CSV}" ] && { $DEBUG "\${REPPFILE_CSV}:${REPPFILE_CSV} reused above file or you can remove and refresh repository info"; return 0; }
+    esac
+
     (( "$(reppversion ver 2>/dev/null)" < 230 )) && {
         reppversion toggle
         warn "automatically update to latest repo version, you can restore 'repp version toggle'"
@@ -771,7 +771,7 @@ function reppmanidb(){
 
     ## make result output
     #declare -p mani_out
-    printf "%s\n" "${mani_out[@]}" >  ${REPPFILE_CSV}
+    printf "%s\n" "${mani_out[@]}" >  ${REPPFILE_CSV}.json
     #current
     local prnmsg='%s|%12.12s|%8.8s|%-32.32s|%-32.32s|%-32.32s|%-74.74s|%.80s'
     printf "${prnmsg}\n" ${mani_out[*]//|/ } > ${REPPFILE_TXT}
@@ -788,25 +788,29 @@ function reppmanidb(){
         cp ${REPPFILE_CSV}.repo ${REPPFILE_CSV};
     fi
 
-    ## compare both only rrev
-    if ! diff -q -B <(awk -v FS="|" '{print $1 $3 $6 $7 $8}' ${REPPFILE_CSV}) <(awk -v FS="|" '{print $1 $3 $6 $7 $8}' ${REPPFILE_CSV}.repo) &>/dev/null ; then
+    ## 핵심colume만 비교하기 위해 추출
+    local matchlinenum_json matchlinenum_repo
+    touch ${REPPFILE_CSV}
+    awk -v FS="|" '{print $1"|"$3"|"$6"|"$7"|"$8}' ${REPPFILE_CSV}.json > ${REPPFILE_CSV}.json.cmp
+    awk -v FS="|" '{print $1"|"$3"|"$6"|"$7"|"$8}' ${REPPFILE_CSV}.repo > ${REPPFILE_CSV}.repo.cmp
+    if ! diff -q -B ${REPPFILE_CSV}.json.cmp ${REPPFILE_CSV}.repo.cmp &>/dev/null
+    then ## json과 repo가 다르다면 (manifest자체에 문제가 있거나, json parsing이 제대로 안된경우)
         warn "${REPP_PATH}/${REPPFILE_MANI}\n        has mismatch  between 'repo manifest' and 'repo forall'"
+        clog "bad case:content different" "join 'repo' and 'json' info"
 
-        ##join from ${REPPFILE_CSV} and ${REPPFILE_CSV}.repo
-        if [ -s ${REPPFILE_JSON} ] && [[ "$(grep -c '' ${REPPFILE_CSV})" -eq "$(grep -c '' ${REPPFILE_CSV}.repo)" ]]; then
-        ## repp.csv와 repp.csv.repo의 라인수가 같은 경우 (세부정보만 다른경우), 세부정보는 repp.csv것(1~5)을 사용한다. 나머지(6~8)는 repp.csv.repo를 사용한다.
-            clog "normal case:" "generated by 'composition' manifest and repo";
-            paste -d'|' <(awk -v FS="|" '{print $1"|"$2"|"$3"|"$4"|"$5}' ${REPPFILE_CSV}) <(awk -v FS="|" '{print $6"|"$7"|"$8}' ${REPPFILE_CSV}.repo) > tempfile
-            mv tempfile ${REPPFILE_CSV}
-        else
-        ## repp.csv와 repp.csv.repo의 라인수가 다른 경우 (repo list가 다른경우), 무조건 repp.csv.repo를 사용한다.
-            #diff -u ${REPPFILE_CSV} ${REPPFILE_CSV}.repo
-            clog "bad case:" "generated by 'repo' only"
-            cp ${REPPFILE_CSV}.repo ${REPPFILE_CSV};
-        fi
-    else
-        ## repp.csv와 repp.csv.repo가 같은 경우 (정상적으로 잘 만들어진경우)
-        clog "good case:" "generated by 'exactly same' repo and manifest"
+        ## repo.cmp파일에서 한줄씩읽어 json.cmp에서 match라인을 찾으면, 해당 라인을 json에서 DB로 넣고, 못찾으면 repo에서 DB로 넣어라
+        while read -r line && [[ -n ${line} ]]; do
+            matchlinenum_json=$(grep -nx "$line" ${REPPFILE_CSV}.json.cmp| cut -d: -f1) ##match라인 num구하기
+            matchlinenum_repo=$(grep -nx "$line" ${REPPFILE_CSV}.repo.cmp| cut -d: -f1)
+            if   (( matchlinenum_json > 0 )); then sed -n ${matchlinenum_json}p ${REPPFILE_CSV}.json >> ${REPPFILE_CSV}
+            elif (( matchlinenum_repo > 0 )); then sed -n ${matchlinenum_repo}p ${REPPFILE_CSV}.repo >> ${REPPFILE_CSV}
+            else err "sever error, please check logic"
+            fi
+        done < ${REPPFILE_CSV}.repo.cmp
+
+    else ## repp.csv.json와 repp.csv.repo가 같은 경우 (정상적으로 잘 만들어진경우)
+        clog "good case:exactly same" "generated from manifest and verfied by repo"
+        cp ${REPPFILE_CSV}.json ${REPPFILE_CSV}
     fi
     bar inline "${REPPFILE_CSV}"
 
@@ -819,7 +823,7 @@ function reppmanidb(){
     #cat ${REPPFILE_JSON}|jq -cC '.project[]|{groups,remote,upstream,"dest-branch",revision,name,path}'
     #cat ${REPPFILE_JSON}|jq -jr '.project[]|.groups,"|",.remote,"|",.upstream,"|",."dest-branch","|",.revision,"|",.name,"|",.path,"\n"'
     #cat ${REPPFILE_JSON}|jq -jr '.project[]|.groups," ",.remote," ",.upstream," ",."dest-branch"," ",.revision," ",.name," ",.path,"\n"'
-    #cat ${REPPFILE_JSON}|jq -cM '.project[]|{groups,remote,upstream,"dest-branch",revision,name,path}'|tr -d '"'
+    #cat ${REPPFILE_JSON}|jq -cM '.project[]|{groups,remote,upstream,"dest-branch",revision,name,path}'|tr -d 'repp"'
 }
 
 
@@ -1549,8 +1553,9 @@ function repp_initvar(){
     REPPFILE_XML=repp.xml                        #repp mani에서 전체 manifest를 하나의 manifest 파일로 생성시 결과파일
     REPPFILE_JSON=${REPP_DIR}/repp.json          #repo manifest로부터 생성된 repo json 파일
     REPPFILE_TXT=${REPP_DIR}/repp.txt            #위 json을 parsing한 결과를 formatted txt로 저장한 파일, 구분자(|)
-    REPPFILE_CSV=${REPP_DIR}/repp.csv            #위 json 파일과 repo forall을 비교하여 최종 생성된 파일 DB, 구분자(|)로 csv로 읽을때는 변환필요.
+    REPPFILE_CSV=${REPP_DIR}/repp.csv            #위 json 파일과 repo forall을 비교하여 최종 생성된 파일 DB, 구분자(|)로 excel로 읽을때는 변환필요.
                                                  #repp.csv항목은 repo forall list와 동일하며, 세부 git정보만 더 포함되어 있다.
+    #repp.csv.json                               #manifest json을 parsin하여 생성된 DB
     #repp.csv.repo                               #repo forall로부터 생성된 DB, json파일로 생성이 어려울때 최종사용하게 된다.
     #repp.csv.lfs                                #repp.csv항목중에 git lfs로 구성된 git list
     #repp.csv.submodule                          #repp.csv항목이 소유한 git submodule list
@@ -3317,7 +3322,10 @@ esac
 ##============================================================================
 REVV_VER=
 GITT_REMOTE= &&GITT_PROJECT= &&GITT_BRANCH= &&GITT_REVIEW= &&GITT_URL= &&GITT_PATH=
-REPP_PATH= &&REPP_ROOT= &&REPP_REMOTE= &&REPP_PROJECT= &&REPP_URL= &&REPP_BRANCH= &&REPP_REPOURL= &&REPP_REF= &&REPP_GROUPS= &&REPP_COUNT= &&REPP_CMD=
+##REPP_PATH=.repo/manifests, REPP_ROOT=src root, REPP_COUNT=total repo count, REPP_CMD=repo command
+###REPP_REMOTE=manifest remote, REPP_URL=manifest git url, REPP_BRANCH=manifest branch, EPP_REPOURL=repo url, REPP_REF=reference path, REPP_GROUPS=group option when repo init,
+REPP_PATH= &&REPP_ROOT= &&REPP_COUNT= &&REPP_CMD=
+REPP_REMOTE= &&REPP_PROJECT= &&REPP_URL= &&REPP_BRANCH= REPP_REPOURL= &&REPP_REF= &&REPP_GROUPS=
 REPP_REMOTELIST=()
 REPP_REVIEWLIST=()
 REPP_PATH_ALL=()
