fix: repp connect

diff --git a/tools/repp b/tools/repp
--- a/tools/repp
+++ b/tools/repp
@@ -444,11 +444,25 @@ function reppinit(){
 # repo init helper
 # $1 short repo init command
     ##option handle
+    
+    case $1 in
+       help|'')    cat <<-EOF
+			ex) repp init -u ssh://${USER}@vgit.lge.com:29440/honda/linux/manifest -b tsu_25.5my_release
+			ex) repp init -b lampauto_s_release -m all.xml
+			ex) repp init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1
+			ex) repp init -u ssh://lamp.lge.com:29420/platform/manifest.git -b lampauto_r_release \
+			     -m lampauto/lampauto-gm-recent.xml --reference=/data001/vc.integrator/mirror/lampauto_r_release/ \
+			     --repo-url=ssh://lamp.lge.com:29420/repo/git-repo.git
+			
+EOF
+            info 'please refer http://collab.lge.com/main/x/wY6wa'
+            return 1
+       ;; *) :
+    esac
+    
     local url revision manifest platform reference depth repo_url extra ret=0
     if ! options=$(getopt -l reference:,depth:,repo-url:,no-clone-bundle,partial-clone,no-tags,mirror -o b:m:p:u: -- "$@")
-    then err 'please check "repo init --help"'; exit 1; fi
-
-    if [ -z $1 ]; then printElement 'please refer http://collab.lge.com/main/x/wY6wa' && exit 1;fi
+    then err 'please check "repo init --help"'; return 1; fi
 
     ##reset legacy positional parameter except $options
     eval set -- "$options"
@@ -471,24 +485,17 @@ function reppinit(){
     done
 
     ##revision handle, if url has lamp
-    if [ -z "${revision}" ] && [ "${url}" != "${url/lamp/}" ]; then
-        printf "usage: repp init -b [branch] [-m manifest.xml] \n";
-        bar outline
-        printf "ex: repp init -b lampauto_s_release -m all.xml \n";
-        printf "ex: repp init -u https://android.googlesource.com/platform/manifest -b android-12.1.0_r1 \n";
-        printf "ex: repp init -u ssh://lampgd1.lge.com:29418/platform/manifest.git -b lampauto_r_release \n -m lampauto/lampauto-gm-recent.xml --reference=/data001/vc.integrator/mirror/lampauto_r_release/ \n --repo-url=ssh://lamp.lge.com:29418/repo/git-repo.git \n";
-        exit
-    fi
+    if [ -z "${revision}" ] && [ "${url}" != "${url/lamp/}" ]; then repp init help; fi
 
     ##url handle with replication server
     local file_info=$(mktemp)
-    if [ -z "${url}" ] || [ "${url}" != "${url/lamp/}" ]; then
-        url="ssh://lamp.lge.com:29418/platform/manifest.git";
-        printf "-u option is necessary";
-        printf "usage: repp init -u ssh://${USER}@vgit.lge.com:29440\n ~~~ ";
-    fi
-    if [ -z "${reference}" ];then reference="${reference:-${path_mirror}/${revision}}"; fi
-    if [ -z "${repo_url}" ] && [ "${url}" != "${url/lamp/}" ];then repo_url='ssh://lamp.lge.com:29418/repo/git-repo.git';fi;
+    # if [ -z "${url}" ] || [ "${url}" != "${url/lamp/}" ]; then
+        # url="ssh://lampba1.lge.com:29420/platform/manifest.git";
+        # printf "-u option is necessary";
+        # printf "usage: repp init -u ssh://${USER}@vgit.lge.com:29440\n ~~~ ";
+    # fi
+    # if [ -z "${reference}" ];then reference="${reference:-${path_mirror}/${revision}}"; fi
+    # if [ -z "${repo_url}" ] && [ "${url}" != "${url/lamp/}" ];then repo_url='ssh://lamp.lge.com:29420/repo/git-repo.git';fi;
 
     cmd_repoinit="repo init ${url:+-u ${url}} ${revision:+-b ${revision}} ${manifest:+-m ${manifest}} ${platform:+-p ${platform}} ${reference:+--reference=${reference}} ${depth:+--depth=${depth}} ${repo_url:+--repo-url=${repo_url}} ${extra} $@"
 
@@ -591,14 +598,23 @@ function reppcheck_gerritconnection(){
 function reppcheck_sshconnection(){
 ## ---------------------------------------------------------------------------
 # run command, get return code and print guide
-    local file_error=$(mktemp)
-    echo "\$ ssh -T $1 -p $2" ;
-    echo . | ssh -T $1 -p $2 2> ${file_error}
+    local server="$1" 
+    local port="$2"
+    local file_error="$(mktemp)"
+    #echo "\$ ssh -T $1 -p $2 -vvv" ;
+    showRUN ssh -T $server -p $port -vvv 2> $file_error
 
-    case $(cat $file_error) in
-     *success*) echo good, it works;;
-     *publickey*) echo check publickey;;
-     *) echo unknown error is occured;;
+    case $(cat ${file_error}) in
+        help)       echo "ssh connection error msg handler"
+    ;; *success*)   echo "good, it works"
+    ;; *Connection?refused*) 
+                    bar outline "check log in ${file_error}"
+                    grep -En "*Connection refused*" $file_error
+                    
+                    bar outline "check IP/PORT setting in (.ssh/config) with below"
+                    ping $server -c2
+    ;; *publickey*) err check publickey
+    ;; *)           echo unknown error is occured, please check log [${file_error}]
     esac
 
     #rm -f ${file_error}
@@ -615,32 +631,39 @@ function reppconnect(){
     local server_port=${REPP_REMOTE#*@}
     local server=${1:-${server_port%:*}}
     local port=${2:-$(echo ${server_port} | grep -oP '(?<=:)[0-9]+(?=/)')}
-    local manifest=${3:-${server_port#*/}}
+    local gitproject=${3:-${server_port#*/}}
     local branch=${4:-${REPP_BRANCH}}
     local ret
 
 
     #local port=$(echo ${server_port} | grep -oP '(?<=:)[0-9]+(?=/)')
-    bar inline "step1: check if ssh is installed"
-    if [ -x "$(command -v ssh)" ]; then  log "ssh is installed in [$(which ssh)]"; else err "ssh is not installed"; fi
-
-    if [ -z $server ] || [ -z $port ];then warn "usage) repp check vgit.lge.com 29420 tiger/tools tiger_release" && return 1;fi
-    bar inline "step2: check if server tcp port is well listened"
+    bar inline "step1: [local] check if ssh is installed"
+    if [ -x "$(command -v ssh)" ]; then  log "ssh is installed in [$(which ssh)]"; else err "ssh is not installed, install it"; fi
+    if [ -z $server ] || [ -z $port ];then warn "usage) repp connect vgit.lge.com 29420 tiger/tools tiger_release" && return 1;fi
+    
+    bar inline "step2: [remote] check if server tcp port is well listened"
     timeout 5 bash -c "</dev/tcp/$server/$port"
-    if [ $? == 0 ];then echo "server $server over port $port is listened"
-    else echo "server $server over port $port is not listened"; fi
+    if [ $? == 0 ];then echo "server $server over port $port is listened"; 
+    else echo "server $server over port $port is not listened, please contact server manager"; fi
 
-    bar inline "step3: check if sshd is serviced on this port $port"
+    bar inline "step3: [remote] check if sshd is serviced on this port $port "
     reppcheck_sshconnection $server $port
 
-    bar inline "step4: check if gerrit service is valid"
+    bar inline "step4: [remote] check if gerrit service is valid"
     reppcheck_gerritconnection ssh $server -p $port gerrit version
 
-    if [ -z $manifest ];then warn "usage) repp check vgit.lge.com 29420 tiger/tools tiger_release" && return 1;fi
-    bar inline "step5: check if I can access git (default: manifest)"
-    ret=$(ssh $server -p $port gerrit ls-projects --prefix ${manifest} -b ${branch})
-
-    echo "can accessed [${ret#* }]"
+    if [ -z $gitproject ];then info "usage) repp connect vgit.lge.com 29420 tiger/tools tiger_release" && return 1;fi
+    if [[ "$gitproject" == *.git* ]]; then err ".git must be removed in [$gitproject]"; fi
+    bar inline "step5: [remote] check if I can access git project"
+    ret=$(ssh $server -p $port gerrit ls-projects --prefix ${gitproject})
+    [ -n "$ret" ] &&  echo "can accessed [${ret}]" || err "check git project path [${gitproject}]"
+    
+    bar inline "step6: [remote] check if I can access the branch (default: master)"
+    [ -z "${branch}" ] && branch="master" || branch="${branch}"
+    ret=''
+    ret=$(ssh $server -p $port gerrit ls-projects --prefix ${gitproject} -b ${branch})
+    [ -n "$ret" ] &&  echo "can accessed [${branch}: ${ret% *}]" || err "check git branch is existed or permission allowed, contact project owner [${branch}]"
+    
 }
 
 
@@ -768,7 +791,7 @@ local MENU=(
     ex) repp connect, repp connect vgit.lge.com 29420 tiger/tools tiger_release
         repp connect [git-server] [port] [project]  [branch]"
 "server: check delay from server or confirm the server status
-    ex) repp server, repp server lamp.lge.com 29418"
+    ex) repp server, repp server lamp.lge.com 29420"
 )
 
     
@@ -1028,8 +1051,8 @@ EOF
                 read -p "to see diff in detail [ enter:contiue| line:compare with line | q(ctrl+c):break ]: " 
                 case "$REPLY" in
                     n) clog "you can use with options:" "git diffi --line-numbers"
-                ;;  line) git diffi --line-numbers
-                ;;  *) git diffi
+                ;;  line) git diffi --line-numbers 
+                ;;  *) git diffi 
                 esac
     esac
 }
@@ -1194,8 +1217,10 @@ function repp(){
 local ret=0
 
 case "$1" in
-       init)        :
-       ;; *)        reppcheck_precondition print_y 
+         init)  : 
+       ;;help|server|connect)  reppcheck_precondition print_n
+       ;;   *)  reppcheck_precondition print_y  
+                [ "$?" -ne 0 ] && return 1
 esac
 
 case "$1" in
@@ -1203,7 +1228,7 @@ case "$1" in
        help)        reppmenu help
     ;; '')          reppmenu "${@:2}"
     ;; info)        reppinfo  "${@:2}"
-    ;; show)        reppshow "${@:2}"  2>&1
+    ;; show)        reppshow "${@:2}"  
     ;; go)          reppgo "${@:2}"
     ;; commit)      reppcommit "${@:2}"
     ;; find|list)   reppfind "${@:2}"
