reppforall verify various command & remove result

diff --git a/tools/repp b/tools/repp
--- a/tools/repp
+++ b/tools/repp
@@ -5,7 +5,7 @@
 ## ==========================================================================
 ###---------------------------------------------------------- DEBUG OPTION
 #DEBUG=["echo -e"|:], : means no-operation
-## DEBUG=[ : | "printf ${RED}%s${NCOL}\n" ]
+#DEBUG=[ : | "printf ${RED}%s${NCOL}\n" ]
 DEBUG=:
 #DEBUG="printf ${RED}%s${NCOL}\n"
 
@@ -273,6 +273,11 @@ REPO_LREV,REPO_GROUP,REPO_REMOTE,REPO_RREV,REPO_PROJECT,REPO_PATH,REPP_SCRIPT,RE
 
         [ "$pro" = ". " ] && pro=${GITT_PROJECT}  #set as current git project
         [ "$pro" = "all" ] && pro='.'             #match all git project
+         [[ $pre = bash*-*c* ]] && pre='bash'             #match all git project
+
+
+        ##repp forall tiger/services/ethmgr tiger/metas/meta-tiger  -cj1 bash -c '[ -z "${REPO_RREV}" ] && echo ${REPO_PROJECT}' $USER $PWD
+        ##            project                                        sep pre     cmd                                             opt
         $DEBUG "pro~~~~~~" "$pro"; $DEBUG "sep~~~~~~" "$sep"; $DEBUG "pre~~~~~~" "$pre";
         $DEBUG "cmd~~~~~~" "$cmd"; $DEBUG "opt~~~~~~" "$opt"; $DEBUG "script~~~~~~" "$REPPFILE_INSCRIPT"
 
@@ -307,42 +312,30 @@ REPO_LREV,REPO_GROUP,REPO_REMOTE,REPO_RREV,REPO_PROJECT,REPO_PATH,REPP_SCRIPT,RE
 1. 아래 명령으로 reppforall.csv를 생성한다.
 2. REPP_SCRIPT 영역에 test에 필요한 command 넣고 저장한다.
 3. repp forall로 위에서 기록한 모든 command를 제대로 실행하는지 확인한다.
-repp forall tiger/services/ethmgr vendor/qct/sa515m/apps_proc/src/data vendor/qct/sa515m/clo/le/OTA/build  vendor/qct/sa515m/clo/le/OTA/system/core -cj1 bash -c 'case ${REPO_RREV} in
-    ext_adp_s|ext_hero_s)
-        git status
-        if [ "${REPO_PROJECT}" = "non_HLOS" ] || \
-           [ "${REPO_PROJECT}" = "platform/Settings" ]; then
-            echo git checkout ${HOME}
-        else
-            git log -1
-        fi;;
-    *) printf "\n------------[${REPO_PATH} $1 $2]\n";;
-esac;' $USER $PWD
-
-REPP_SCRIPT 항목에 한 cell에 한명령씩 넣어야 함
-bash -c /data001/vc.integrator/mirror/tsu_26my_release/src_current/.repp/reppscript.sh aaa bbb
+bash /data001/vc.integrator/mirror/tsu_26my_release/src_current/.repp/reppscript.sh - $USER $PWD
 /data001/vc.integrator/mirror/tsu_26my_release/src_current/.repp/reppscript.sh
-"bash -c 'case ${REPO_RREV} in
+bash -c 'case ${REPO_RREV} in
     ext_adp_s|ext_hero_s)
         git status
         git log -1
-    ;;*) printf "\n------------[${REPO_PATH} $1 $2]\n"
-esac;'  $USER $PWD"
+    ;;*) printf "\n------------${REPO_PATH}[%s]\n" "$1 $2"
+esac;' - $USER $PWD
 echo "${REPO_REMOTE}:${REPO_PROJECT}:${REPO_PATH}:${REPO_LREV}:${REPO_RREV}"
 revv accessall ${REPO_REMOTE} ${REPO_PROJECT}
-"bash -c 'case ${REPO_RREV} in
+bash -c 'case ${REPO_RREV} in
     ext_adp_s|ext_hero_s)
         git status
         if [ "${REPO_PROJECT}" = "non_HLOS" ] || \
            [ "${REPO_PROJECT}" = "platform/Settings" ]; then
-            echo git checkout ${HOME}
+            echo ${HOME}
         else
             git log -1
-        fi;;
-    *) printf "\n------------[${REPO_PATH} $1 $2]\n";;
-esac;'  $USER $PWD"
+        fi
+    ;;*) printf "\n------------${REPO_PATH}[%s]\n" "$1 $2"
+esac;' - $USER $PWD
 
 TEST
+
 
 function reppforall(){
 ## ---------------------------------------------------------------------------
@@ -396,8 +389,8 @@ EOF
     readarray -d $'\r\n' -t arrayline < <(cat "$REPPFILE_FORALL"| awk 'BEGIN{FS=","; RS="\r\n"; OFS="`"; ORS="\r\n"; found=0} /^REPO_LREV/ {found=1; next} found && ($1 !~ /^[0-9a-f]{10,}/ || $7 ~ /[[:print:]]+/) \
     {gsub(/("|=)/,"",$1); gsub(/""/,"\"",$7); gsub(/\r/,"",$7);print $1"`"$2"`"$3"`"$4"`"$5"`"$6"`"$7}')
 
-    ## reppforall_result.csv에 실행결과를 출력한다.
-    cat "$REPPFILE_FORALL"| awk '$1~/REPO_LREV/ {print; exit} {print}' > ${REPPFILE_FORALL%\.*}_result.csv
+    ## 결과값을 reppforall_result.csv에 write하려고 했으나, 다중 script를 호출하는 구조로 return값 처리가 어려워서 보류
+    ## cat "$REPPFILE_FORALL"| awk '$1~/REPO_LREV/ {print; exit} {print}' > ${REPPFILE_FORALL%\.*}_result.csv
 
     ##REPO_XXX로 시작하는 heading 을 제외하고 그 다음줄 부터 처리, count=1
     ##먼저 실행할 내용을 보여주고
@@ -420,10 +413,10 @@ EOF
 
     ## repp forall 입력시 전체를 어떻게 실행할지 1회 물어본후, 각 명령어 실행시미다 다시 물어본다.
     local opt ask outfile cmd= pro=
-    local __ret='NONE'
-    read -p $'\n\n[enter:execute by asking |go:run all| ctrl+c:break] :' opt
+    read -p "$(echo -e "\n\n${cyan}[enter:execute by asking |go:run all| ctrl+c:break]:${NCOL}")" opt
+    if [ "$opt" != "" ] && [ "$opt" != "go" ]; then err "you have to input either 'enter' or 'go' "; return 1 ; fi
 
-    > $REPPFILE_TMSCRIPT.csv
+
     touch $REPPFILE_TMSCRIPT && chmod +x $REPPFILE_TMSCRIPT
     for ((count=0,total=0; count<${#arrayline[@]}; count++ )); do
         readarray -t -d\` oneline <<< "${arrayline[$count]}"
@@ -436,11 +429,25 @@ EOF
         if [[ -z "$cmd" ]];then continue; fi
 
         ## 현재 context에서 실행을 위해 source로 file로 만들어 호출한다.
-        bbar cyan "" "\n"
         if [ -f "${cmd}" ]; then cmd=". ${cmd}"
         else ##command 자체를 file로 변환하여 처리
-            #echo "${cmd}"| awk 'BEGIN {RS=""; FS="\n"} {gsub(/^['\''"]|['\''"]$/, ""); print}' "~~~"만 삭제
-            echo "${cmd}"| awk 'BEGIN {RS=""; FS="\n"} {gsub(/^["'\''"]|["'\''"]$/, ""); print}' > $REPPFILE_TMSCRIPT #"~~~", '~~~'둘다 삭제
+            ## 입력된 command의 특수문자나 잘못된 quote나 error 구문이 있는지 검사한다.
+            #echo "${cmd}"| awk 'BEGIN {RS=""; FS="\n"} {gsub(/^['\''"]|['\''"]$/, ""); print}'   #"~~~"만 삭제
+            #"~~~", '~~~'둘다 삭제, 아래 구문은 정확히 동작하는것 같지가 않음. 그냥 현상태 유지바람.
+            cmd=$(echo "${cmd}"| awk 'BEGIN {RS=""; FS="\n"} {gsub(/^["'\''"]|["'\''"]$/, ""); print}')
+            if [ -z "${cmd%%\'*}" ]; then
+                err "remove wrapping single quotes('~~~') from command\n"
+                wave; echo $cmd; return 1
+            fi
+            if [ -z "${cmd%%\"*}" ]; then
+                err "remove wrapping double quotes(\"~~~\") from command\n"
+                wave; echo $cmd; return 1
+            fi
+            if  echo "${cmd}" |grep '? '; then warn "remove special character from command" ; fi
+            if ! echo "${cmd}" | bash -n; then err "input command is not correct!"; return 1; fi
+
+            ## 문제가 없으면 repp_inscript.sh로 넣는다.
+            echo "${cmd}" > $REPPFILE_TMSCRIPT; #"~~~", '~~~'둘다 삭제
             cmd=". $REPPFILE_TMSCRIPT"
         fi
 
@@ -452,16 +459,17 @@ EOF
         under "[$((total=total+1))] ${oneline[4]}\n"
         bbar cyan "${oneline[5]}" "$(cat $REPPFILE_TMSCRIPT)\n"
         ## 각 repository마다 다시 한번씩 물어보게 된다. go를 입력하면 나머지는 물어보지 않고 바로 실행한다.
-        [ "$opt" = "" ] && read -p '[enter:run next| go:run all| other:skip next| ctrl+c:break all] :' ask;
+        read -p "$(echo -e "\n\n${yellow}[enter:run next| go:run all| other:skip next| ctrl+c:break all]:${NCOL}")" ask
         if [ -z "$ask" ]; then pushd "$REPP_ROOT/${oneline[5]}";
             REPO_ROOT="$REPP_ROOT" REPO_LREV="${oneline[0]}" REPO_GROUP="${oneline[1]}" REPO_REMOTE="${oneline[2]}" REPO_RREV="${oneline[3]}" REPO_PROJECT="${oneline[4]}" REPO_PATH="${oneline[5]}" ${cmd}
-            [ $? -eq 0 ] && __ret='OKAY' || __ret='FAIL'
-            #windows파일인지 linux파일인지 판단
-            if [ "$fileencoding" = "windows" ];
-            then awk -v count="$((count+3))" -v ret="$__ret" 'BEGIN{RS=ORS="\r\n"} NR==count {print $0,ret}' "$REPPFILE_FORALL" >> ${REPPFILE_FORALL%\.*}_result.csv
-            else awk -v count="$((count+3))" -v ret="$__ret" 'BEGIN{RS=ORS="\n"} NR==count {print $0,ret}' "$REPPFILE_FORALL"   >> ${REPPFILE_FORALL%\.*}_result.csv
-            fi
 
+            # ## REPP_RESULT값이 설정되지 않았을때에 대한 default값 설정
+            # if [ "$__ret" = "NONE" ]; then [ $? -eq 0 ] && __ret='OKAY' || __ret='FAIL'; fi
+            # #windows파일인지 linux파일인지 판단
+            # if [ "$fileencoding" = "windows" ];
+            # then awk -v count="$((count+3))" -v ret="$__ret" 'BEGIN{RS=ORS="\r\n"} NR==count {print $0,ret}' "$REPPFILE_FORALL" >> ${REPPFILE_FORALL%\.*}_result.csv
+            # else awk -v count="$((count+3))" -v ret="$__ret" 'BEGIN{RS=ORS="\n"} NR==count {print $0,ret}' "$REPPFILE_FORALL"   >> ${REPPFILE_FORALL%\.*}_result.csv
+            # fi
             popd
         elif [ "$ask" = "go" ]; then opt=go; ask=''
         else
