fix screen path, update repp/gitt go

diff --git a/tools/repp b/tools/repp
--- a/tools/repp
+++ b/tools/repp
@@ -192,7 +192,7 @@ function reppinfo(){
 ## ---------------------------------------------------------------------------
 # print information of repo
 # $1 manifests file (default is current manifests)
-    local manifest=${1:-${REPPFILE_MANI}}
+    local manifest=$1
 
     pushd ${REPP_PATH}
     #oldIFS=${IFS}; IFS='';
@@ -207,7 +207,7 @@ function reppinfo(){
     ##show manifest file with included sub manifests.
     bar inline "manifests"
     clog  "    <name of manifest>                                      <including branches>"
-    reppshow_manifesttree ${manifest} 0
+    reppshow_manifesttree ${manifest:-${REPPFILE_MANI}} 0
     
     ##show count of repository
     ### block infomation
@@ -257,47 +257,50 @@ function reppshow(){
 
 
 
+# local menu_items=('go ROOT　dir' 'go Manifests　dir' 'go GIT　root dir' 'exit')
+# run_menu "${menu_items[@]}"
+# case "$?" in
+	# 1|11)  cd "${REPP_ROOT}"        ;;
+	# 2|12)  cd "${REPP_PATH}"        ;;
+# esac
+
 function reppgo() {
 ## ---------------------------------------------------------------------------
 # return git root path or return near git path
     local cmd="$1"
 
     case $cmd in
-        root)  cd "${REPP_ROOT}"                    && return 0 ;;
-        mani)  cd "${REPP_PATH}"                    && return 0 ;;
-        git)   cd "$(gittcheck_gitpath print_y)"    && return 0 ;;
-    esac
+        repo)     cd "${REPP_ROOT}"     && return 0 ;;
+        mani)     cd "${REPP_PATH}"     && return 0 ;;
+        git)      cd "${GITT_PATH}"     && return 0 ;;
+    esac 
 
-    local menu_items=('go ROOT　dir' 'go Manifests　dir' 'go GIT　root dir' 'exit')
-    run_menu "${menu_items[@]}"
-    case "$?" in
-        1|11)  cd "${REPP_ROOT}"        ;;
-        2|12)  cd "${REPP_PATH}"        ;;
-    esac
-    
-    dest=.git
-    local T=$(pwd)
-    if [ "${REPP_ROOT}" = "${T}" ]; then
-        echo "your are in repo root, use 'repp find @path' to list up all repositories" && return 0;
+    local INPUT=( $(find ${REPP_ROOT}/.. -maxdepth 4 -name ".repo" 2> /dev/null |head -60))
+    if [ -n "${INPUT}" ];
+	then run_menu "${INPUT[@]}";  cd "${menu_selected}/.."
+	else INPUT=( $(find ${HOME} -maxdepth 4 -name ".repo" 2> /dev/null |head -60))
+		 run_menu "${INPUT[@]}";  cd "${menu_selected}/.."
     fi
+}
 
-    ##find path to upper dirs until HOME or ROOT.
-    dirs -c
-    while [ "$T" != "$HOME" ] && [ "$T" != "/"  ]; do
-        T=$PWD
-        if [ -d "$T/${dest}" ]; then cd $T && return 0; fi
-        pushd .. > /dev/null
-    done
 
-    ##not found in partents, now findout in child
-    pushd -0 && dirs -c > /dev/null
-    #echo "no .git found, stay HERE"
 
-    local INPUT=( $(find ../.. -maxdepth 4 -name "${dest}" 2> /dev/null |head -60))
-    #local INPUT=( $(reppfind @path) )
+function gittgo() {
+## ---------------------------------------------------------------------------
+# return git root path or return near git path
+    local cmd="$1"
 
-    if [ -n "${INPUT}" ];then run_menu "${INPUT[@]}" ;  fi
-    cd "${menu_selected}/.."
+	reppcheck_initvar print_n
+    case $cmd in
+        repo)     cd "${REPP_ROOT}"     && return 0 ;;
+        mani)     cd "${REPP_PATH}"     && return 0 ;;
+        git|'')   cd "${GITT_PATH}"     && return 0 ;;
+    esac
+
+    local INPUT=( $(awk -v FS="|" '{print $5}' ${REPPFILE_CSV} |grep $cmd| sort) )
+	
+    if [ -n "${INPUT}" ]; then run_menu "${INPUT[@]}"; cd "${REPP_ROOT}/${menu_selected}" 
+	else reppfind $cmd; warn "you must cd manually to dir"; fi
 }
 
 
@@ -324,12 +327,12 @@ function reppcommit(){
             ;;
     esac
 
-    echo "repo forall -c \"git log -1 --abbrev=6 --date=format:'%Y-%m-%d %H:%M:%S' --pretty=format:'%ad  %h  [%an] %d %s%n'\" |sort -r |head -${count:-50}"
+    echo "repo forall -c \"git log -1 --abbrev=6 --date=format:'%Y-%m-%d %H:%M:%S' --pretty=format:'%ad  %h  [%an] %(describe:abbrev=0) %s%n'\" |sort -r |head -${count:-50}"
     echo "> $out"
 
     bar outline "repo get recent commit"
     bar inline "date:YMD HMS]       [sha]   [author]      [commit title]                                            [git project                            branch"
-    repo forall -j16 -c 'printf "%-100.100s %-80s \n" "$(git log -1 --abbrev=6 --date=format:"%Y-%m-%d %H:%M:%S" --pretty=format:"%ad  %h  [%an] %s")" "[${REPO_PROJECT}  ${REPO_RREV}]"' |sort -r |head -${count:-50} > $out
+    repo forall -j16 -c 'printf "%-100.100s %-80s \n" "$(git log -1 --abbrev=6 --date=format:"%Y-%m-%d %H:%M:%S" --pretty=format:"%ad  %h  [%an] %s")" "[${REPO_PROJECT}  ${REPO_RREV}]"' |grep -v skip| sort -r |head -${count:-50} > $out
     #repo forall -c "git log -1 --abbrev=6 --date=format:'%Y-%m-%d %H:%M:%S' --pretty=format:'%ad  %h  [%an] %d %s%n'" |sort -r |head -${count:-50} > $out
 
 }
@@ -352,11 +355,11 @@ function reppfind(){
 
     case ${cmd} in
       comment) @로 시작하면 coloume을 출력
-    ;; @rev)      echo "REPO_LREV";    awk -v FS="|" '{print $1}' ${REPPFILE_CSV}
-    ;; @remote)   echo "REPO_REMOTE";  awk -v FS="|" '{print $2}' ${REPPFILE_CSV} |sort |uniq
-    ;; @branch)   echo "REPO_RREV";    awk -v FS="|" '{print $3}' ${REPPFILE_CSV} |sort |uniq
-    ;; @project)  echo "REPO_PROJECT"; awk -v FS="|" '{print $4}' ${REPPFILE_CSV} |sort
-    ;; @path)     echo "REPO_PATH" > /dev/stderr;   awk -v FS="|" '{print $5}' ${REPPFILE_CSV} |sort
+    ;; @rev)      echo "<REPO_LREV>";    awk -v FS="|" '{print $1}' ${REPPFILE_CSV}
+    ;; @remote)   echo "<REPO_REMOTE>";  awk -v FS="|" '{print $2}' ${REPPFILE_CSV} |sort |uniq
+    ;; @branch)   echo "<REPO_RREV>";    awk -v FS="|" '{print $3}' ${REPPFILE_CSV} |sort |uniq
+    ;; @project)  echo "<REPO_PROJECT>"; awk -v FS="|" '{print $4}' ${REPPFILE_CSV} |sort
+    ;; @path)     echo "<REPO_PATH>";    awk -v FS="|" '{print $5}' ${REPPFILE_CSV} |sort
     ;; "")        printf "\e[1;33m%6.6s %7.7s %-22.22s %-74.74s %.80s \e[0m\n" "REPO_LREV" "REPO_REMOTE" "REPO_RREV" "REPO_PROJECT" "REPO_PATH"
                   cat ${REPPFILE_CSV} | tee  >(wc -l)
     ;; *)         printf "\e[1;33m%6.6s %7.7s %-22.22s %-74.74s %.80s \e[0m\n" "REPO_LREV" "REPO_REMOTE" "REPO_RREV" "REPO_PROJECT" "REPO_PATH"
@@ -578,7 +581,7 @@ function reppversion(){
         under "you need to upgrade 'repo' to use full functionality\n"
 		clog "1. remove old .repo:" rm -rf ${REPP_ROOT}/.repo
 		clog "2. download to dir:" git clone https://gerrit.googlesource.com/git-repo ${path_mirror}/repo2 --mirror
-		clog "3. replace repo and repo init:" [--repo-url=${REPP_URL}] --\> [${path_mirror}/repo2]
+		clog "3. repo init with below command:" --repo-url=[${REPP_URL}] --\> [${path_mirror}/repo2]
         pushd ${REPP_PATH} ; reppget_repcmd info ; popd
 		clog "-->"
         echo "${REPP_CMD/${REPP_URL}/${path_mirror}/repo2}"
@@ -609,11 +612,13 @@ function reppcheck_sshconnection(){
     local port="$2"
     local file_error="$(mktemp)"
     #echo "\$ ssh -T $1 -p $2 -vvv" ;
-    showRUN ssh -T $server -p $port -vvv 2> $file_error
+	echo "ssh -T $server -p $port -vvv 2> $file_error"
+    echo \n| ssh -T $server -p $port -vvv 2> $file_error
 
     case $(cat ${file_error}) in
         help)       echo "ssh connection error msg handler"
     ;; *success*)   echo "good, it works"
+					return 0
     ;; *Connection?refused*) 
                     bar outline "check log in ${file_error}"
                     grep -En "*Connection refused*" $file_error
@@ -663,7 +668,6 @@ function reppconnect(){
         help) echo "repp connect vgit.lge.com 29420 tiger/tools tiger_release"; return 1;
     ;;     *) :
     esac
-
 
     local server_port=${REPP_REMOTE#*@}
     local server=${1:-${server_port%:*}}
@@ -763,7 +767,7 @@ function reppfind_repodir(){
 
 
 
-function reppcheck_precondition(){
+function reppcheck_initvar(){
 ## ---------------------------------------------------------------------------
 # pre-check
 # $1 command
@@ -788,7 +792,7 @@ function reppcheck_precondition(){
 	REPPFILE_STATUS=${REPP_ROOT}/repp.status
 	REPPFILE_COMMIT=${REPP_ROOT}/repp.commit
 	REPPFILE_CSV=${REPP_ROOT}/repp.csv
-	REPPFILE_XML=repp.csv
+	REPPFILE_XML=repp.xml
 
     if [[ $ret -eq 1 && "$1" = "print_y" ]]; then
         printf "%s\n" ${REPP_PATH_ALL[@]};
@@ -914,7 +918,7 @@ done
 
 
 
-function gittcheck_gitpath(){
+function gittcheck_initvar(){
 ## ---------------------------------------------------------------------------
     ##readarray -t GITT_REMOTE < <(git remote -v |cut -f1|uniq)
     GITT_REMOTE=$(git remote|head -1)
@@ -937,7 +941,6 @@ function gittinfo(){
     local TEMP
     local review_gerrit=admin/repos
     bar inline "git path"
-    if ! gittcheck_gitpath print_y ;then echo "we are not in git project" && return 1; fi
 
     ## "error: must check" must be checked!!!
     bar inline "show all remote info"
@@ -1002,8 +1005,8 @@ function gittshow(){
     showRUN git log --decorate --graph -n${depth} --pretty=format:'%Cred%h -%C(yellow)%s %Cgreen(%ci) %C(blue)<%an>%Creset' 
 
     bar inline "git commit diff history"
-    echo "--since(=after), --before(=until)"
-    echo "6 hour, 2-day, 2-week, 1-month, 1-year"
+    echo "filter: --since(=after), --before(=until)"
+    echo "date  : 6 hour, 2-day, 2-week, 1-month, 1-year"
     clog "ex:" "--since=2-weeks, --since=04:24, --before=6-hours, --after=2022-11-10 --before=2022-11-20-23"
     read -p "input add option [enter(default):--pretty="short" --name-only | input option with default]"
 
@@ -1083,26 +1086,15 @@ function gittcommit(){
        help)    cat <<-EOF
 				usage) gitt commit help $1
 				usage) gitt commit auto      #add auto commit				
+				usage) gitt commit reset     #show useful reset command 
 				usage) gitt commit           #show commit info and diff with cached
 				usage) gitt diff help        #show diff with specific rev
 EOF
     ;; auto)    msg=$(date +"%y%m%d:%H%M")
-                git commit -m "${msg}: ${1:-test}"
+                git commit -m "${msg}: ${opt:-test}"
                 git show --stat --oneline HEAD
                 clog "[run]" "git push $GITT_REMOTE HEAD:refs/heads/${GITT_BRANCH}"
-    ;; reset)   cat <<-EOF
-				guide) git reset flow
-				1) git log: check reset point in repository
-				2) git reset <rev> <option>
-				   current : repository index workspace| current status
-				    --soft :      >>>>> index workspace| keep commit & file, retry from 'git push' 
-				    --mixed:            >>>>> workspace| keep only  file, retry from 'git add' (default)
-				    --hard :                     >>>>> | remove all, retry from scratch
-				3) retry from each step
-				flow) git log> git reset c3cef36787        > add modification> git add -A> git commit        > git push
-				flow) git log> git reset c3cef36787 --soft > add modification> git add -A> git commit --amend> git push
-				info) 'git reset --hard' restored by this 'git reflog > git reset --hard <relog rev>'
-EOF
+    ;; reset)   gittreset help
     ;;     *)   formatprint git status -s --porcelain
                 printf "\n\n"
                 read -p "to see diff with cached in detail [ enter:compare| line:compare with line | q(ctrl+c):break ]: " 
@@ -1261,13 +1253,31 @@ function gittreset(){
 
     local cmd=$1
     case ${cmd} in
-        all)  repo forall -cj${NJOBS} 'git reset --hard ; git clean -xdf'
-              echo "reset all repositories" 
-    ;; ''|*)  if gittcheck_isgitproject; then
-                showRUN git reset --hard; showRUN git clean -xdf
-              else
-                warn "this is not a git directory";
-              fi
+         all)   repo forall -cj${NJOBS} 'git reset --hard ; git clean -xdf'
+                echo "reset all repositories" 
+    ;; clear)   if gittcheck_isgitproject; then
+                    showRUNQ y "git reset --hard; showRUN git clean -xdf"
+                else
+                    warn "this is not a git directory";
+                fi
+    ;;  help) 	cat <<-EOF
+				usage) gitt reset clear #remove all changes and reset
+				usage) gitt reset       #show detail reset commands
+EOF
+    ;;     *)   cat <<-EOF
+				guide) git reset flow
+				1) git log: check reset point in repository
+				2) git reset <rev> <option>
+				   current : worksapce index repository | description
+				   -----------------------------------------------------------------------------------------------------
+				    --soft : workspace index <<<<       | keep commit & file, retry from 'git push' 
+				    --mixed: workspace <<<<             | keep only  file, retry from 'git add' (default)
+				    --hard : <<<<                       | remove all, retry from scratch
+				3) retry from each step
+				flow) git log> git reset c3cef36787        > add modification> git add -A> git commit        > git push
+				flow) git log> git reset c3cef36787 --soft > add modification> git add -A> git commit --amend> git push
+				info) 'git reset --hard' restored by this 'git reflog > git reset --hard <relog rev>'
+EOF
     esac
 }
 
@@ -1278,7 +1288,9 @@ function gitt(){
 # main handler for this scriptre
 # $1 command
 local ret=0
-if ! gittcheck_gitpath print_n;then err "we are not in git project" && return 1; fi
+
+if ! gittcheck_isgitproject; then err "we are not in git project" && return 1; 
+else gittcheck_initvar print_n; fi
 
 case "$1" in
     ##$1:below ${@:2}:parameters
@@ -1286,13 +1298,13 @@ case "$1" in
     ;;      '')     gittmenu "${@:2}"          
     ;;    info)     gittinfo 
     ;;    show)     gittshow "${@:2}"
-    ;;      go)     cd "${GITT_PATH}"     
+    ;;      go)     gittgo "${@:2}"
     ;;  commit)     gittcommit "${@:2}"
     ;;  branch)     gittbranch "${@:2}"        
     ;;    find)     gittfind "${@:2}"
     ;;    diff)     gittdiff "${@:2}"
     ;;   reset)     gittreset "${@:2}"
-    ;;   debug)     reppdebug "${@:2}"
+    ;;   debug)     gittdebug "${@:2}"
     ;;       *)     bar outline "call native git"
                     git "${@}";;
 esac
@@ -1308,9 +1320,9 @@ function repp(){
 local ret=0
 
 case "$1" in
-         init)  : 
-       ;;help|server|connect)  reppcheck_precondition print_n
-       ;;   *)  reppcheck_precondition print_y  
+         init|go)  : 
+       ;;help|server|connect)  reppcheck_initvar print_n
+       ;;   *)  reppcheck_initvar print_y  
                 [ "$?" -ne 0 ] && return 1
 esac
 
@@ -1346,11 +1358,11 @@ function reppdebug(){
 #repo forall -c 'echo ${REPO_REMOTE}:${REPO_PROJECT}:${REPO_PATH}:${REPO_LREV}:${REPO_RREV}'
     
     if ! gittcheck_isgitproject; then pushd ${REPP_PATH}; fi
-    gittcheck_gitpath print_n ; 
+    gittcheck_initvar print_n ; 
     popd
     
     source <(cat <<\EOL
-        bar inline "GITT_VARIABLE && REPP_VARIABLE"
+        bar inline "GITT_VARIABLE && REPP_VARIABLE for all repository"
         for var in \
         '${GITT_PROJECT}' '${GITT_REMOTE}' '${GITT_BRANCH}' '${GITT_REVIEW}' '${GITT_URL}' '${GITT_PATH}' \
         '${REPP_PATH}' '${REPP_ROOT}' '${REPP_REMOTE}' '${REPP_BRANCH}' '${REPP_URL}' '${REPP_MIRROR}' '${REPP_COUNT}' \
@@ -1365,6 +1377,28 @@ function reppdebug(){
         bar inline "[all repo] print repo variable"
         dlog                '${REPO_COUNT}, ${REPO_LREV}, ${REPO_REMOTE}, ${REPO_RREV}, ${REPO_PROJECT}, ${REPO_PATH}, ${REPO_OUTERPATH}, ${REPO_INNERPATH}'
         repo forall -c 'echo ${REPO_COUNT}, ${REPO_LREV}, ${REPO_REMOTE}, ${REPO_RREV}, ${REPO_PROJECT}, ${REPO_PATH}, ${REPO_OUTERPATH}, ${REPO_INNERPATH}' | more -60
+EOL
+)
+    ##run echo
+}
+
+
+
+function gittdebug(){
+## ---------------------------------------------------------------------------
+#reppdebug & gittdebug
+#repo forall -c 'echo ${REPO_REMOTE}:${REPO_PROJECT}:${REPO_PATH}:${REPO_LREV}:${REPO_RREV}'
+    
+    source <(cat <<\EOL
+        bar inline "GITT_VARIABLE && REPP_VARIABLE for this git"
+        for var in \
+        '${GITT_PROJECT}' '${GITT_REMOTE}' '${GITT_BRANCH}' '${GITT_REVIEW}' '${GITT_URL}' '${GITT_PATH}' 
+        do
+           dlog "$var\t" $(eval echo $var)
+        done
+
+        bar inline "[${GITT_PROJECT}] print REPO variable using repo"
+        showRUN repo forall . -c 'echo ${REPO_COUNT}, ${REPO_LREV}, ${REPO_REMOTE}, ${REPO_RREV}, ${REPO_PROJECT}, ${REPO_PATH}, ${REPO_OUTERPATH}, ${REPO_INNERPATH}'
 EOL
 )
     ##run echo
